### ISSUE TITLE
Autocompletion of identifiers not working in some cases

### ISSUE THREAD

**Issue by atrieu** [cpitclaudel/company-coq#10]
When defining mutually recursive theorems/lemmas using the following method:

Theorem foo: ...
with bar: ...
Proof. ... Qed.

Later, the autocompletion doesn't work for bar, but works for foo.

**Comment by cpitclaudel** [comment]
True, thanks for noticing this! "with" is missing from the list of definition keywords, I'll add it.
Ideally though I'd really like https://github.com/coq/coq/pull/56 to get merged; this would make name completion much more robust (and much better: it wouldn't be restricted to the names defined in the current buffer).
