### ISSUE TITLE
Completion does not work on Coercions in the current file

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#101]
This works:
```coq
Definition foooooo (x : nat) : Set := nat.
Check foo
```
![image](https://cloud.githubusercontent.com/assets/396076/14393736/72341f82-fd96-11e5-9f0d-1435156e7881.png)
But this does not:
```coq
Coercion foooooo (x : nat) : Set := nat.
Check foo
```
![image](https://cloud.githubusercontent.com/assets/396076/14393745/80b95702-fd96-11e5-96d7-0f4d279292de.png)

**Comment by cpitclaudel** [comment]
Just to make sure: this is with the completion patch, right?
