### ISSUE TITLE
Leave empty line after folded code

### ISSUE THREAD

**Issue by jstolarek** [cpitclaudel/company-coq#102]
I have a feature request about code folding. Let's say I have this code (shamelessly stolen from the tutorial):

```coq
Fixpoint MkLarge {A} d (l ll:A) :=
  match d with O => TrL ll | S n => TrB (MkLarge n l l) (MkLarge n l ll) end.

Lemma inH: forall T n (t: T), inhabited (Tt (@MkLarge Type n T T)).
  intros; constructor; induction n; simpl; constructor; eauto. Qed.
```
If I now fold definition of `MkLarge` I get:

```coq
Fixpoint MkLarge {A} d (l ll:A) := [...]
Lemma inH: forall T n (t: T), inhabited (Tt (@MkLarge Type n T T)).
  intros; constructor; induction n; simpl; constructor; eauto. Qed.
```

But I would like to keep an empty line between folded definition and `inH` lemma:

```coq
Fixpoint MkLarge {A} d (l ll:A) := [...]

Lemma inH: forall T n (t: T), inhabited (Tt (@MkLarge Type n T T)).
  intros; constructor; induction n; simpl; constructor; eauto. Qed.
```
I find that much easier to read.

**Comment by cpitclaudel** [comment]
That would be lovely. Do you use code folding for bullets, or only to get an outline? If it's only for an outline, then

```elisp
(setq company-coq-features/code-folding-ellipsis "[…]\n")
```

is probably a pretty good solution.

(One would hope to be able to do something like

```elisp
(setq company-coq-features/code-folding-ellipsis
      (concat "[…]" (propertize "\n" 'line-spacing 0.5)))
```

or

```elisp
(setq company-coq-features/code-folding-ellipsis
      (concat "[…]" (propertize "\n" 'line-height '(nil . 1.5))))
```

but that doesn't work).

**Comment by cpitclaudel** [comment]
Alternatively, we could patch outline-minor-mode to not fold blank space, by advising `outline-flag-region` with this:

```elisp
(when flag
  (save-excursion
    (goto-char to)
    (skip-chars-backward " \t\r\n")
    (setq to (point))))
```

**Comment by cpitclaudel** [comment]
Yet another trick (that one might be the easiest one, actually, and it doesn't break folded bullets either):

```elisp
(setq-local outline-regexp (concat "\n" company-coq-outline-regexp))
```

**Comment by cpitclaudel** [comment]
One more: we could run this after each folding/unfolding:

```elisp
  (dolist (ov (overlays-in (point-min) (point-max)))
    (when (eq (overlay-get ov 'invisible) 'outline)
      (overlay-put ov 'after-string "\n"))))
```

**Comment by jstolarek** [comment]
I don't use bullets, so I went with your first suggestion. I also tried the third one but for some reason I couldn't make it work.

**Comment by cpitclaudel** [comment]
Cool. I'll close the issue then :) I think I'll implement something based on the third approach in company-coq soonish. There's definitely space for improvement in this domain.
