### ISSUE TITLE
compan-coq can't find documentation is /usr/local

### ISSUE THREAD

**Issue by jstolarek** [cpitclaudel/company-coq#103]
I have Coq installation built from sources under linux. By default it is installed under `/usr/local`. Documentation is stored in `/usr/local/share/doc/coq/` and it seems that company-coq is unable to find it. Typing `C-h` says "No documentation available".

Note that I am not entirely certain that my documentation is installed properly. The above documentation directory contains: `html`, `pdf` and `ps` directories as well as two files: `FAQ-CoqIde` and `LICENSE.doc`. `html` directory contains `faq`, `refman` and `stdlib` directories with lots of html files. Is that expected contents of documentation directory?

**Comment by cpitclaudel** [comment]
Hi,

company-coq doesn't look for locally installed documentation (it ships its own fork of the docs; Coq's documentation isn't properly annotated to be searchable). Can you post a small snippet with instructions to reproduce this “No documentation available” message?

Thanks!

**Comment by jstolarek** [comment]
I am working my way through the tutorial. On the line 61 where it says to type `appl C-h` I do exactly that and in the status line I get "No documentation available". Is that enough information to reproduce the problem?

I have company-coq installed from melpa. Is it possible that this version is missing documentation? Where should I look for company-coq documentation (I want to verify that it is really where it should be)?

**Comment by cpitclaudel** [comment]
Thanks! Yes, that's enough information to pinpoint the problem :) But not to reproduce it, unfortunately.

Let's see. The docs for this particular tactic should be in `~/.emacs.d/elpa/company-coq-(some-version-number)/refman/6s.html.gz`. Installing from MELPA is totally fine (and preferred).

Can you take a screenshot of Emacs showing message?

**Comment by jstolarek** [comment]
I checked and I have all the documentation files in `refman` directory. Here's a screenshot just a moment after typing `C-h` (error message at the bottom):

![company-coq](https://cloud.githubusercontent.com/assets/1597921/14472283/bea8667a-00f2-11e6-8d85-ede366b9fe73.png)

Also, here is my Emacs configuration file: https://github.com/jstolarek/scripts/blob/master/emacs/.emacs Perhaps something in my configuration triggers the problem.

**Comment by cpitclaudel** [comment]
Thanks. That looks like company's message, so company-coq must be returning nil. Hmm.
Please let me know which version of Emacs you're using; with that, I should have enough info to reproduce the issue, hopefully! :)

**Comment by jstolarek** [comment]
My Emacs version is 24.5.1 compiled from sources with some custom settings that I don't remember.

**Comment by cpitclaudel** [comment]
Thanks.

**Comment by cpitclaudel** [comment]
Hi,

I'm a bit confused. I downloaded your .emacs, tried to guess which packages you were using and installed them in a fresh Emacs 24.5, installed company-coq from MELPA, and ran this experiemnt, but everything works fine for me.

It could be one of the few packages that I could not install, such as rect-mark. Other than that, I'm not sure.

Could you try to use a smaller .emacs with just company-coq and proof-general, maybe?

**Comment by jstolarek** [comment]
I just reduced my `.emacs` to this and the problem still persists:

```
;; Load path
(add-to-list 'load-path "~/.emacs.d/elpa/")
(add-to-list 'load-path "~/.emacs.d/idris-mode")
(add-to-list 'load-path "~/.emacs.d/other-exts")

;; ProofGeneral
(load-file "~/.emacs.d/other-exts/ProofGeneral/generic/proof-site.elc")
(add-hook 'coq-mode-hook #'company-coq-mode)
```

**Comment by cpitclaudel** [comment]
Cool. Do you need to actually need idris-mode and elpa in your `load-path`? Which proof-general are you using?

**Comment by jstolarek** [comment]
You're right - I don't need this. So now I have this config:

```
(add-to-list 'load-path "~/.emacs.d/other-exts")
(load-file "~/.emacs.d/other-exts/ProofGeneral/generic/proof-site.elc")
(add-hook 'coq-mode-hook #'company-coq-mode)
```
But the problem remains. I am using PG from github at commit ProofGeneral/PG@dbfe0a4

**Comment by cpitclaudel** [comment]
Ok. Let me try to reproduce again then.

**Comment by cpitclaudel** [comment]
Ok. I ran the following commands (using [`Cask`](https://github.com/cask/cask)):

```
$ cd /scratch/
$ mkdir GH-103
$ cd GH-103/
$ cask init
$ printf '\n(depends-on "company-coq")' >> Cask 
$ EMACS=emacs-24.5 cask install
$ EMACS=emacs-24.5 cask exec emacs-24.5 -Q
```

Then I executed the following in the resulting fresh Emacs:

```elisp
(load-file "~/.emacs.d/lisp/ProofGeneral/generic/proof-site.elc")
(add-hook 'coq-mode-hook #'company-coq-mode)
(require 'company-coq)
(company-coq-tutorial)
```

With that, I couldn't reproduce the issue; the docs worked properly.

I wonder what's causing your issue :/

**Comment by jstolarek** [comment]
Tomorrow I'll try to install Cask and see if the above steps reproduce the problem on my machine.

**Comment by cpitclaudel** [comment]
Cool; thanks!

**Comment by jstolarek** [comment]
Ok, I just installed Cask and followed the steps above. I can still reproduce my problem. Is it possible that this feature relies on something that I might have not compiled into my Emacs? For example, I compiled Emacs without X support.

**Comment by jstolarek** [comment]
Here's how I configured my Emacs before building:

```
./configure --without-all --with-x=no --with-file-notification=yes --with-zlib
```

**Comment by cpitclaudel** [comment]
Ah, of course :)

**Comment by cpitclaudel** [comment]
Your build doesn't include libxml, so company-coq can't parse Coq's html documentation.

**Comment by cpitclaudel** [comment]
I could certainly produce a more explicit error message, though.

**Comment by cpitclaudel** [comment]
Just to confirm: `M-: (fboundp 'libxml-parse-html-region)` is `nil`, right?

**Comment by jstolarek** [comment]
Yes, that's it! I recompiled emacs with `--with-xml2` and now help works without problems. I'm leaving this report open as a reminder to implement more informative error message :)
