### ISSUE TITLE
Feature Request: Folding on Proof

### ISSUE THREAD

**Issue by gmalecha** [cpitclaudel/company-coq#104]
It seems like you can only fold bullets at the moment. It would be nice if you could also fold an entire Proof block, e.g.

```
Lemma foo : True /\ True.
Proof.
   tauto.
Qed.
```

would fold into:

```
Lemma foo : True /\ True.
Proof. [..] Qed.
```

**Comment by cpitclaudel** [comment]
Hey Greg,

Yup, I have a bit of code to do this, but it's non trivial to integrate it cleanly with the bullet folding code. Did you try C-c C-/ though? It's not very far from doing that (although it does hide the body of lemmas, which is suboptimal)

**Comment by gmalecha** [comment]
Ah, I didn't see that in the tutorial. Folding the type of the lemma unfortunately isn't what I need since what I'm hoping to do is look through the list of lemmas and understand the abstractions that are there.

**Comment by cpitclaudel** [comment]
Yup, makes sense. Emacs' folding facilities are a bit limited, but I've been looking at other packages, such as [origami](https://github.com/gregsexton/origami.el/issues/20). Ideally, it would be nice to get a parse tree from Coq, since parsing on the Emacs side is virtually impossible.

**Comment by gmalecha** [comment]
I think that I mentioned this at CoqPL, but @Ptival has been working on similar things in PeaCoq. The last demo I saw was reconstructing the AST and he was able to highlight appropriately. I think there is a plugin involved, but getting better parsing support if you have a plugin would be fine by me.

**Comment by cpitclaudel** [comment]
Sure :) I just need some time to investigate this, and I don't have much :/

Another idea. What about running this before `C-c C-/`?

```elisp
(setq-local outline-heading-end-regexp "\\.[ \t\n]")
```

**Comment by nickgian** [comment]
+1 this would be very nice to have in future versions of company-coq (folding of proofs only, not definitions).

**Comment by cpitclaudel** [comment]
@nickgian can the following settings in a Coq buffer:

```elisp
(setq-local outline-heading-end-regexp "\\.[ \t\n]")
(setq-local outline-regexp (concat "\n" company-coq-outline-regexp))
```

And then `C-c C-/`

**Comment by cpitclaudel** [comment]
@co-dan This shouldn't be needed anymore — the default behavior changed recently-ish when I merged the experimental branch.  Do you see a difference after running that code?

**Comment by co-dan** [comment]
@cpitclaudel  I was using the ELPA version. I still haven't figured out how to install Cask packages from source. Will get back to this issue once i figure this out.

**Comment by cpitclaudel** [comment]
Yup, I should have closed this :) Thanks for testing!
(btw, the MELPA version should be up-to-date; isn't it?)

**Comment by co-dan** [comment]
Maybe. I was just using an older version probably
