### ISSUE TITLE
intros! ignores some of ProofGeneral settings

### ISSUE THREAD

**Issue by jstolarek** [cpitclaudel/company-coq#105]
Say I have:

```coq
Goal forall a b c, a -> b -> c -> a.
  intros!X(guess names)
```
where `X` marks the position of the cursor and `(guess names)` is suggestion by company-coq. If I press RET I get the following:

```coq
Goal forall a b c, a -> b -> c -> a.
  intros a b c X0 X1 X2.
  X
```
Two undesirable things have happened here:
1. Firstly, I have set `coq-one-command-per-line` to `nil`, which means I don't want to move to a new line after command is terminated with a dot. So far it seems that auto-completion for all other commands follows this setting. `intros!` is an exception that ignores it and moves me to a new line. I want it to move me to a new line only if I enable `coq-one-command-per-line`.
2. I have enabled `proof-electric-terminator-enable`, which means that inserting a terminator (dot) triggers proof checking. This is not happening with the `intros` generated by company-coq, which forces me to manually trigger proof advancement to introduce variables into the context. Again, I would like company-coq to follow my settings and automatically advance the proof if electric terminator is enabled.

**Comment by jstolarek** [comment]
Oops, this bug report got sent too early. Sorry about that. I edited the description to contain full details.

**Comment by cpitclaudel** [comment]
Good points, thanks!

**Comment by cpitclaudel** [comment]
I've open a corresponding Proof General bug report, as the issue is on the PG side (company-coq just calls an internal PG function).

**Comment by cpitclaudel** [comment]
I've written a patch for PG @ https://github.com/ProofGeneral/PG/pull/68 ; let's track this issue there.

**Comment by cpitclaudel** [comment]
Fixed on the PG side; please test :)

**Comment by jstolarek** [comment]
It works. :-) One minor thing I would modify is not adding a space after a dot (again, consistence with behaviour of other autocompletion commands).
