### ISSUE TITLE
company-coq changes input methods to accept umlauts

### ISSUE THREAD

**Issue by jstolarek** [cpitclaudel/company-coq#107]
company-coq changes the input method to accept umlauts: typing `"s` results in `ß`, typing `"O` results in `Ö` and so on. This is mostly unexpected (at least for someone using a language without umlauts).

**Comment by jstolarek** [comment]
I just realized it's not just about umlauts. `'` is also interpreted as a special character by the input method. And so: `'c` leads to 'ć', `'n` leads to `ń` and so on.

**Comment by cpitclaudel** [comment]
I don't think it's company-coq. Are you sure about this?

**Comment by jstolarek** [comment]
Frankly speaking, no. I just tried reproducing this on my home machine and I can't. Which is mostly surprising given that both machines have identical versions of emacs, PG and company-coq and use the same configuration file. I'll look into this tomorrow when I get to work.

**Comment by jstolarek** [comment]
I can't reproduce this any more :-/ Whatever the problem was it seems to have gone away. Closing.

**Comment by jstolarek** [comment]
Interesting - this seems to happen on a random basis, but only on one of my machines. Restarting Emacs solves the problem (for some time).
