### ISSUE TITLE
Smarter auto-complete for Hints

### ISSUE THREAD

**Issue by jstolarek** [cpitclaudel/company-coq#109]
Let's say I want to type `Hint Unfold foo`. When I type `Hint` I get auto-completion that contains 34 suggestions (sic!) and the one for `Unfold` is somewhere at the bottom of the list. What I would expect is that I can keep typing, say until `Hint Unf` and at that point suggestions are reduced only to those beginning with the above phrase. However, once I insert space after `Hint` all suggestions for `Hint` disappear and when I type `Unf` I get suggestions unrelated to `Hint` command. It would be great if autocompetion behaved smarter in the context of Hints.

**Comment by cpitclaudel** [comment]
Yup, it's annoying, Can you have a look at https://github.com/cpitclaudel/company-coq/issues/49 and tell me if you think it is related? If so, we can track everything under that number.

**Comment by jstolarek** [comment]
Yes, this is exactly the same. Closing this in favour of #49
