### ISSUE TITLE
intros! does not work

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#110]
After switching to Coq 8.5pl1 trying to use intros! I get the following error:

`Company: backend company-coq-master-backend error "Symbol's function definition is void: string-empty-p" with args (post-completion intros! (guess names)`

**Comment by cpitclaudel** [comment]
Hii there,

I don't think this is specific to Coq; it's probably more of an Emacs version issue.
Can you remind me which version of Emacs you use?

**Comment by cpitclaudel** [comment]
Urgh, my bad. It's due to a recent change that I made on the proof-general side.

**Comment by cpitclaudel** [comment]
Can you try upgrading proof general? I just pushed (what I hope to be) a fix.

**Comment by vzaliva** [comment]
Thanks! I am right now in the middle of the process of re-installing COQ on my laptop, but I will check and report back as soon as I will get it working.

**Comment by vzaliva** [comment]
I just checked and it works now. Thanks!

**Comment by vzaliva** [comment]
It works. Thanks!
