### ISSUE TITLE
Inserting a unicode character with a 2-character code

### ISSUE THREAD

**Issue by fidget324** [cpitclaudel/company-coq#111]
I have noticed that autocompletion for unicode symbols kicks in when 3 characters have been entered. For instance, the autocomplete box drops down when I type the "t" in "\bet". But it's not clear how one can enter a unicode character when the LaTeX sequence is only two characters. For example, I would like to use the LaTeX symbol "\in". But when I type "\in" company-coq will not autocomplete the symbol.

**Comment by cpitclaudel** [comment]
Try C-RET (Control-enter) after typing "\in"; does that help?

**Comment by fidget324** [comment]
No, but I'm also working at a terminal, and I think the RET key might be behaviorally different in the terminal. For instance I had to remap C-c C-RET to C-c RET for proof-goto-point.

**Comment by cpitclaudel** [comment]
Ah, of course :/ Try `company-manual-begin`

**Comment by fidget324** [comment]
Yes, that command did work. Thanks!

**Comment by cpitclaudel** [comment]
Great :) I'll close this, but I'll think on my side to ways of making completion kick in earlier for math symbols (but only for those, since it slows things to do fully general completion for 2-character prefixes).
