### ISSUE TITLE
`Include` lacking completions

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#112]
I get completions for `Import`, but not for `Include`:
![image](https://cloud.githubusercontent.com/assets/396076/15021676/3141d5cc-11f6-11e6-96eb-76ce9e285c7d.png)
![image](https://cloud.githubusercontent.com/assets/396076/15021681/375283c6-11f6-11e6-82bc-709c279af8b8.png)

**Comment by cpitclaudel** [comment]
True; though for Include we'd want all modules, not just files. Is there a way to enumerate those?

**Comment by JasonGross** [comment]
Not that I know of: https://github.com/cpitclaudel/company-coq/issues/113#issuecomment-216939952

**Comment by cpitclaudel** [comment]
Let's merge this with #113 :)
