### ISSUE TITLE
assert isn't deprecated in 8.5, so why is this usage so tagged?

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#118]
Seems like there is some crosstalk going on between that deprecation underlining of assert and the record construction syntax:
![screenshot-assert v-1](https://cloud.githubusercontent.com/assets/7363878/15490729/bbbe017a-2138-11e6-80bb-51a837da5574.png)

**Comment by cpitclaudel** [comment]
Yup, you're spot on. Yet another case of "regular expressions are hard": the deprecated form is `assert (x := _)`.

I''ll push a fix-ish soon.

**Comment by cpitclaudel** [comment]
Thanks for the report, btw!

**Comment by cpitclaudel** [comment]
Note to self: just enforce identifier syntax between `(` and `:=`
