### ISSUE TITLE
[M-RET] Add support for "Inductive"

### ISSUE THREAD

**Issue by Malabarba** [cpitclaudel/company-coq#12]
First of all, thanks for this great extension.

Secondly, it would be great if `company-coq-insert-match-rule-simple` also worked on other situations that are similar to (but not the same as) `match` rules.

For instance hitting `M-RET` at the end of the following

    Inductive day : Type :=
    | monday : day

Could yield the following

    Inductive day : Type :=
    | monday : day
    | _ :

**Comment by cpitclaudel** [comment]
Thanks for the nice comments! <kbd>M-RET</kbd> and <kbd>M-S-RET<kbd> can actually take a <kbd>C-u</kbd> prefix argument to insert inductive constructors; my reasoning for moving them to `C-u` was mostly that inductive constructors are not written as often as match cases.

I wonder if there are other situations in which `M-RET` would be needed, in which case a context aware version of `insert-match-rule` would be in order (but navigating Coq's syntax is tricky :/)

**Comment by Malabarba** [comment]
Oh, I wasn't aware of the prefix argument. That should do for now. :)
I've only just started learnig, but I can imagine how complicated coq syntax can be.

**Comment by cpitclaudel** [comment]
Great; I'll close this then. 
Also: I'm a big fan of Endless Parentheses, so if you find things to improve in company-coq, feel free to share feature requests or patches; I'll be happy to look at them :)

**Comment by Malabarba** [comment]
Sure. If I end up using coq a lot, I'm sure I'll find something to PR.
In the least, I'll probably mention this package on the blog over the next couple of weeks.

Cheers
