### ISSUE TITLE
Global instances now shown by (company-coq-occur)

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#129]
```
Global Instance Foo ...
Instance Bar ...
```

Pressing `C-c C-,` shows _Bar_ but not _Foo_.

**Comment by cpitclaudel** [comment]
Thanks Vadim! I have a fix ready and I'll push it in a few days (I'm in deadline mode atm :/)

**Comment by vzaliva** [comment]
;)

**Comment by vzaliva** [comment]
This fix is not yet in MELPA package (20160715.344). When do you plan to release it?

**Comment by vzaliva** [comment]
@cpitclaudel , sorry for being insistent. Do you plan to update MELPA package soon? It is been a month since the bug was fixed and I am still not being able to see the fix.

I am hesitant to switch to git snapshot of company-coq, but it looks like I will have to do this if MELPA package is no longer updated.

**Comment by vzaliva** [comment]
I customized my `.emacs` to set `company-coq-definitions-kwds` as in suggested patch. However, it still does not show global instances in outline.

**Comment by vzaliva** [comment]
I had manual patch applied which made this work, but after upgrading via MELPA to version 20170110.1633 it is broken again. It looks like somehow the patch https://github.com/cpitclaudel/company-coq/commit/c5c679000ba6afb6ecbec994fd7c3a5da50a1b6d  was not included in MELPA version.

```
company-coq-definitions-kwds is a variable defined in `company-coq.el'.
Its value is
("Class" "CoFixpoint" "CoInductive" "Coercion" "Corollary" "Declare Module" "Definition" "Example" "Fact" "Fixpoint" "Function" "Functional Scheme" "Inductive" "Instance" "Lemma" "Let" "Ltac" "Program" "Program Definition" "Program Fixpoint" "Record" "Scheme" "Theorem" "Variant" "with")

```

**Comment by vzaliva** [comment]
A related issue (not sure if warrants a new ticket) is that `company-coq-definitions-kwds` variable could not be customized in .emacs in mode initialization hook. Hence there is no workaround for this ticket. A user could change it but before this change is applied this variable is used to generate regexp from old values which are no affected after you change the `company-coq-definitions-kwds`.

To sum up the status of this ticket:

1. Git repo has correct version since 4(!) months ago
2. MELPA package still uses old code without this patch
3. There is no way to fix it via .emacs

The current workaround is to stop using MELPA version of company-coq and install it manually, compiled from git snapshot.

Frankly, the fact that MELPA package was not updated for at least 4 months makes me concerned about future support of this excellent and useful product. It will be sad if it dies and we all have to switch to coqide instead.

**Comment by cpitclaudel** [comment]
> There is no way to fix it via .emacs

I don't understand this part

> Frankly, the fact that MELPA package was not updated for at least 4 months makes me concerned about future support of this excellent and useful product. It will be sad if it dies and we all have to switch to coqide instead.

I use it regularly, but I don't want to merge the experimental branch without taking the time to test it, and I don't have much time to do that.  Probably this week-end — at least that's my hope.  If you have time to test the experimental branch, that would be great :) It should be pretty easy too (just an `(add-to-list 'load-path "~/path-to-company-coq-checkout")` in your .emacs)

**Comment by cpitclaudel** [comment]
Thanks.  I promise I'll try to merge things this week-end.  My inbox is looking a bit hectic these days :/

**Comment by cpitclaudel** [comment]
Phew; finally pushed :) Can you confirm it works?

**Comment by vzaliva** [comment]
Just checked and it works! Thanks!

**Comment by cpitclaudel** [comment]
Phew! Well that took a while ^^ Sorry for all the delays.
