### ISSUE TITLE
company-coq-jump-to-definition does not work in the current buffer

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#141]
I have partially interpreted buffer, and I try to jump to a definition defined earlier (in already interpreted part) using `M-.`

Result: Not Found
Expected Result: jump to this definitions

`M-.` works well for definitions from other files/buffers.

**Comment by cpitclaudel** [comment]
Sorry for the delay. Can you post a concrete example? It mostly works for me.

**Comment by vzaliva** [comment]
Here is the example:

```
Definition  a: nat:=1.
Definition  b: nat:=1.

Goal a = b.

```

1. Press `C-c b`
2. Position cursor on 'a' in the `a = b`
3. Press `M-.`

Actual result: Message "a.v not found" in status line.

Expected result: Jump to definition of 'a'.

**Comment by cpitclaudel** [comment]
Thanks.  Can you post the contents of the *coq* buffer? This works for me in a clean Emacs install with just PG and company-coq, so I must be missing something :/

**Comment by vzaliva** [comment]
Interestingly if I open it in fresh emacs, it works! When I open one of the files in the project I work on (in other driectory) and then this one, it does not. Maybe some settings from `_CoqProject` file affects this. But I assume it should not affect files opened in another directory. Here is the _CoqProject:

```
-R "." Top
-I "."

```




Coq buffer:

```
<prompt>Coq < 3 || 0 < </prompt>Add Search Blacklist "Private_" "_subproof". 

<prompt>Coq < 4 || 0 < </prompt>Set Printing Depth 50 . 

<prompt>Coq < 4 || 0 < </prompt>Remove Search Blacklist "Private_" "_subproof".  Add Search Blacklist "Private_" "_subproof". 

<prompt>Coq < 6 || 0 < </prompt>
<prompt>Coq < 7 || 0 < </prompt>Set Printing Width 90.

<prompt>Coq < 8 || 0 < </prompt>Set Silent. 

<prompt>Coq < 8 || 0 < </prompt>Definition  a: nat:=1.

<prompt>Coq < 10 || 0 < </prompt>Definition  b: nat:=1.

<prompt>Coq < 11 || 0 < </prompt>Unset Silent. 

<prompt>Coq < 11 || 0 < </prompt>Goal a = b.
1 subgoal, subgoal 1 (ID 2)
  
  ============================
  a = b

(dependent evars: (printing disabled) )


<prompt>Unnamed_thm < 13 |branch| 0 < </prompt>Timeout 1 Locate Ltac a.
No tactic of basename
a

<prompt>Unnamed_thm < 14 |branch| 0 < </prompt>Timeout 1 Check {| a := _ |}.
Toplevel input, characters 19-20:
> Timeout 1 Check {| a := _ |}.
>                    ^
Error: a: Not a projection

<prompt>Unnamed_thm < 14 |branch| 0 < </prompt>Timeout 1 Locate a.
Constant Top.a

<prompt>Unnamed_thm < 16 |branch| 0 < </prompt>Timeout 1 Locate Library Top.a.
Toplevel input, characters 25-30:
> Timeout 1 Locate Library Top.a.
>                          ^^^^^
Error: Cannot find a physical path bound to logical path matching suffix Top.

<prompt>Unnamed_thm < 16 |branch| 0 < </prompt>

```

**Comment by cpitclaudel** [comment]
Company-coq is getting confused by `-R "." Top`, I think.  The problem is that `Top` is an internal name used by coqtop to mean "the current buffer".  Can you explain what that line means?

**Comment by vzaliva** [comment]
Before going into specifics about 'Top`, let us discuss how settings are propagated. Let us say I have 2 directories with the following layout:

```
a/
  a.v
  _CoqProject
b/
  b.v

```
I open file `a.v` and `_CoqProject` is loaded and used (good).
Then I open file `b.v`.  As it is located in a different directory which does not have `_CoqProject` file (or in a more general case may have a differen one), the settings from the `a/` should not apply here. But it looks like they do.

I think this is the main problem here.

**Comment by cpitclaudel** [comment]
I think this is due to Proog General using global variables for its state, instead of buffer-local ones: `_CoqProject` settings are applied to the entire Emacs session, not just the current buffer.  It's consistent with only having one script buffer at a time, but I agree that it's a pain.

I'm not sure there's anything I can do about this on the company-coq side, though :/

**Comment by vzaliva** [comment]
I have opened a PG issue for this https://github.com/ProofGeneral/PG/issues/152

Let me research why I have the `Top` in my project file. I will add more info here later.

**Comment by cpitclaudel** [comment]
Thanks a lot!

**Comment by vzaliva** [comment]
I checked and `Top` was remains from some old experiments. I removed it and it helped.
Thanks!

**Comment by cpitclaudel** [comment]
Neat, thanks!
