### ISSUE TITLE
company-coq.el:82:1:Error: Symbol's function definition is void: cl-struct-define

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#142]
I recently updated company-coq, and now it doesn't work with Emacs 24.  I get
```
Error: Symbol's function definition is void: cl-struct-define
```
whenever I execute company-coq-mode.  (I might have done something wrong by trying to update some packages while running emacs 26 and then opening emacs 24...)

**Comment by cpitclaudel** [comment]
I'm not sure which version you mean by Emacs 26, but generally packages are not compatible across versions; does reinstalling company-coq fix this?

**Comment by JasonGross** [comment]
Oh, I had to reinstall not just company-coq, but some of its dependencies as well.  Is there a way to tell different versions of emacs to install packages to different locations?

**Comment by cpitclaudel** [comment]
http://emacs.stackexchange.com/questions/13250/how-do-i-run-multiple-versions-of-emacs-with-the-same-emacs-d :/
