### ISSUE TITLE
Change predefined unicode symbol

### ISSUE THREAD

**Issue by yforster** [cpitclaudel/company-coq#147]
Hi,

I'd like to change the appearance of some Unicode symbols that are already defined.

However, doing for instance
```
(add-hook 'coq-mode-hook
          (lambda ()
            (setq-local prettify-symbols-alist
                        '(("<->" . ?⟷)))))
```
does not work (note that this is the longleftrightarrow instead of the leftrightarrow symbol). I suspect it doesn't work because company-coq overwrites the setting for "<->" afterwards.

Is there a hook where I can set prettify-symbols-alist that overwrites company-coq's defaults?

Many thanks in advance
Yannick

**Comment by cpitclaudel** [comment]
Hi Yannick,

Did you try `M-x customive-variable company-coq-prettify-symbols-alist`?

**Comment by yforster** [comment]
Hi Clement,

I did not, and that works indeed. Thanks!

**Comment by cpitclaudel** [comment]
Perfect, thanks for testing!
