### ISSUE TITLE
Document buffer occupies full frame

### ISSUE THREAD

**Issue by LukeXuan** [cpitclaudel/company-coq#148]
The document occupies the frame sorely automatically when I trigger the company-tooltips, unless I manually make the frame split vertically or horizontally. Is there any idea or is this the intended behavior?

Also I observe both the tooltip and a new buffer will be opened, which seems quite messy.

**Comment by cpitclaudel** [comment]
Sorry for the delay.  I'm not sure I understand the issue entirely.  Are you using company-quick-help, or are you describing something different?

**Comment by LukeXuan** [comment]
The screenshot before I press `M-h` to show `company tooltips`, 
![image](https://cloud.githubusercontent.com/assets/3363954/22632985/aa91ba7c-ec58-11e6-9ee2-f7c4c5eaf8f3.png)

And this is the screenshot after,
![image](https://cloud.githubusercontent.com/assets/3363954/22633007/d22545fe-ec58-11e6-82e4-b412d9764a17.png)

**Comment by cpitclaudel** [comment]
Thanks.  Can you clarify where these company tooltips come from? They are not provided by `company` itself, as far as I know, and indeed company-coq isn't compatible with `company-quickhelp`.  Instead, company-coq indeed uses a separate buffer.

**Comment by LukeXuan** [comment]
Interesting. I'm just following spacemacs's [configuration](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bcompletion/auto-completion#tooltips) here, from the code it seems like its based on quickhelp.

**Comment by LukeXuan** [comment]
If the `comany-coq` isn't compatible with that I think this issue can be closed, but I'm wonder is there any plan to be compatible?

**Comment by cpitclaudel** [comment]
https://github.com/expez/company-quickhelp/issues/28 tracks this; I just haven't had much time for it, since I don't use quickhelp myself.  Ok to close this issue?

**Comment by LukeXuan** [comment]
Yes.

**Comment by cpitclaudel** [comment]
Thanks :) I'll bump up quickhelp compatibility in my task list. I'll post again here when appropriate.
