### ISSUE TITLE
Font Beautification Adds Extra Whitespace Padding

### ISSUE THREAD

**Issue by mmalvarez** [cpitclaudel/company-coq#15]
Hello again,

As before, awesome work on this plugin! I had gone for a while without updating it, and it looks like you've added some exciting new features.

However, I notice a problem with the font beautification: some symbols (the "mathcal" symbols for Prop and Nat, as well as some of the arrows) get inserted with a large amount of space above and below them, as you can see in the following picture:

![font-prettify](https://cloud.githubusercontent.com/assets/2506825/7760973/67ceaaea-ffd5-11e4-8bf6-d796aa162b0e.png)

(There should be no whitespace above the line I selected, and only one line of whitespace below; but there is a great deal of whitespace that's been added to the line to "pad" the script P)

Right now I'm using DejaVu Sans Mono as my font, although this problem seems to happen regardless of what font I choose. Also, I am on emacs 24.4.1, on Ubuntu 15.04, using the current MELPA version of company-coq.

Best,
Mario

**Comment by cpitclaudel** [comment]
Hi Mario,

Emacs is using a fallback font, but incorrectly detecting the line height (that's arguably a bug. Can you try the customization described at https://github.com/cpitclaudel/company-coq#empty-squares-in-place-of-math-operators-or-incorrect-line-spacing ? It should fix it hopefully. I find that the `Symbola` font works well (it's available in the `ttf-ancient-fonts` package on Debian systems)

By the way, neat color theme! Is it one of the built-in ones?

**Comment by mmalvarez** [comment]
Clement,

Thanks for the information! I guess I didn't see your expanded Troubleshooting section. Registering Symbola as a fallback font in the way you describe seems to have solved my problem.

I use the Dichromacy color theme; it's designed for users with red-green color-blindness, and I find it more readable than most other themes I've tried.

--Mario

**Comment by cpitclaudel** [comment]
Glad the Symbola trick worked. If you're interested, there's a thread about this problem currently ongoing at http://lists.gnu.org/archive/html/bug-gnu-emacs/2015-05/msg00696.html

Thanks for the Dichromacy pointer!
