### ISSUE TITLE
company-coq-lemma-from-goal does not work with helm-mode

### ISSUE THREAD

**Issue by yforster** [cpitclaudel/company-coq#151]
Hi,

`company-coq-lemma-from-goal` does not work with `helm-mode`. I can choose the hypotheses I want, but pressing `C-j` doesn't do anything. The only way to leave the mode where I can choose is to choose all or abort.

Disabling `helm-mode` solves the problem (or clearing all unwanted hypotheses first and choosing all by repeatedly pressing enter).

Is this a problem of helm or company-coq?

Many thanks in advance
Yannick

**Comment by cpitclaudel** [comment]
Thanks for the report.  I don't use Helm, so maybe you can help me understand this.  With regular completion, pressing C-j returns (picks) an empty string.  Can you do that with Helm?

**Comment by yforster** [comment]
I asked Google what C-j does in helm-mode, and indeed the issue seems to be that it does not pick the empty string (read this [here](https://github.com/emacs-helm/helm/issues/700#issuecomment-62265768)). Both `C-RET` and `M-RET` do pick the empty string though and `company-coq-lemma-from-goal` works perfectly using those shortcuts. 

So the issue seems not really to be about the behaviour, but more about the in this case misleading "or C-j when done" help text.

**Comment by cpitclaudel** [comment]
Thanks a lot! I've pushed an update to the `experimental` branch to clarify the prompt (it also adds an explicit `[done]` entry to the list.

Do you think you could try the `experimental` branch? I intend to merge it this week-end, but it has accumulated a number of changes, so testing help would be most welcome :)

**Comment by yforster** [comment]
Sure. However, `cask install` and `EMACS="emacs-25.1" cask install` don't seem to install company-coq. Any ideas what's wrong? (I installed company-coq from (M?)ELPA before, so don't know more about cask than a quick read over the cask manual told me.

**Comment by cpitclaudel** [comment]
Ugh, sorry for the delay.  No need to make install; you can just `(add-to-list 'lod-path "~/path-to-company-coq-checkout/")`

**Comment by yforster** [comment]
Thanks! The prompt is working perfectly now, both `C-RET` and the explicit `[done]` entry work using helm.

**Comment by cpitclaudel** [comment]
Great, thanks so much for testing.  Merging the experimental branch is on my todo list for today.
