### ISSUE TITLE
Flycheck frame opens unexpectedly

### ISSUE THREAD

**Issue by yforster** [cpitclaudel/company-coq#152]
Hi,

sometimes (I think after using company-coq / Proof General for a couple of hours) if there's an error in the script a flycheck frame opens and takes focus. This is really annoying. Sadly, I'm not able to reproduce this after closing the frame and I don't see a pattern when exactly it opens.

However, I don't need this popup (but would like to keep `flycheck-mode` enabled). Any ideas on how I can disable the popup?

Many thanks in advance
Yannick

**Comment by cpitclaudel** [comment]
Hi Yannick,

Sorry for the delay.  I'm a bit confused by this report: neither company-coq nor Proof General rely on flycheck.  Do you enable Flycheck separately, and if so are you describing a bad interaction between Flycheck and Proof General?

**Comment by yforster** [comment]
Ooops. Apparently, emacs prelude (which I'm using) sets `global-flycheck-mode`, so that's why flycheck is enabled. And yes, I now think I am indeed describing a bad interaction between flycheck and PG, so it's probably not company-coq related and this issue can be closed. Thanks anyways!
