### ISSUE TITLE
company-coq-diff-dwim: "Window is dedicated to ‘*response*’" then "Proof process busy!"

### ISSUE THREAD

**Issue by SkySkimmer** [cpitclaudel/company-coq#156]
In the company coq tutorial get to where it says "Company-Coq supports this: try it with ‘C-c C-a C-d’.  Type ‘q’ to exit." Do the "C-c C-a C-d", do NOT type q to exit, then advance past the abort.
The abort (and anything after it you try to advance past) will be highlighted as though it was being processed but nothing will actually be done. Coqtop needs to be killed.
![Screenshot](https://i.imgur.com/VJTIiA6r.png)

**Comment by cpitclaudel** [comment]
Thanks, I can reproduce this.

**Comment by cpitclaudel** [comment]
If you have time to try the fix-156 branch, it would be great :)

**Comment by SkySkimmer** [comment]
I see that the README says
```
Installing from source

Use Cask.
```
However I don't know how to do that.

**Comment by cpitclaudel** [comment]
Yeah, that's not super helpful.  Given that you already have the dependencies set up, you should be able to just `git clone`, and then use `(add-to-list 'load-path "where-you-cloned")` and then `(require 'company-coq)`

**Comment by SkySkimmer** [comment]
Thanks, it's fixed on my machine.

**Comment by cpitclaudel** [comment]
Ok; thanks!  I'll merge after a few more days of testing.  Feel free to ping me if this isn't merged in a week!

Thanks again for spotting this and testing the fix :)

**Comment by CarlOlson** [comment]
I'm getting this:
```
company-coq-state-change: Window is dedicated to ‘*response*’
proof-shell-ready-prover: Proof process busy!
```

I'll try fix-156, but are you gonna merge it soon?

**Comment by cpitclaudel** [comment]
Yup, probably this week-end :) If you can test it before that, that would be great.

**Comment by CarlOlson** [comment]
Still doesn't work. I'm on OSX, but I'll try Linux tonight.
```
Starting: coqtop -emacs
Capability detection complete: dynamic completion is available.
Hit M-x proof-layout-windows to reset layout
M-x proof-prf for goals; M-x proof-layout-windows refreshes [2 times]
Starting coq process... done.
Error running timer ‘company-coq-maybe-reload-each’: (error "Window is dedicated to ‘*response*’")
cl--assertion-failed: Assertion failed: (eq proof-shell-busy queuemode)
proof-shell-ready-prover: Proof process busy!
```

**Comment by cpitclaudel** [comment]
Thanks.  In that case, please open a separate bug report, and we can try to see what's going on.  A recipe to reproduce the problem would be most welcome :)
