### ISSUE TITLE
Resources not found

### ISSUE THREAD

**Issue by socumbersome** [cpitclaudel/company-coq#157]
On GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9), when I:
1) use the `http://melpa.org/packages/`repository, then installing `company-coq` fails with "url-insert-file-contents: http://melpa.org/packages/math-symbol-lists-20160302.1431.tar: Not found"
2) use the `https://stable.melpa.org/packages/` repository, then installing `company-coq` fails with "url-insert-file-contents: https://stable.melpa.org/packages/math-symbol-lists-1.1.el: Not found"

What should I do?

**Comment by socumbersome** [comment]
Duh, I'm just starting with Emacs and found out that `package-refresh-contents` suffices to fix that.
Sorry!

**Comment by cpitclaudel** [comment]
No problem, glad you fixed it!
