### ISSUE TITLE
Make show-parens-mode and prettify-symbols-mode optional

### ISSUE THREAD

**Issue by lunaryorn** [cpitclaudel/company-coq#16]
Hello,

how can I prevent `company-coq` from enabling `show-parens-mode` and `prettify-symbols-mode`?

The former is redundant for me since I use Smartparens, and I find the latter pretty distracting, and rather prefer to see my Coq source as is.

**Comment by cpitclaudel** [comment]
Would something like this work?

```elisp
(defun customize-company-coq ()
  (show-paren-mode -1)
  (prettify-symbols-mode -1))
(add-hook 'coq-mode-hook #'customize-company-coq t)
```

**Comment by lunaryorn** [comment]
It would, but for this approach I'd much prefer a
company-coq-initialize-hook which is guaranteed to run after company coq
initialisation.  That's just less brittle than relying on the order of
functions in a single hook.

But generally I think that a package should not encode personal preferences
of its maintainers an developers.  IOW I think the proper place for
Prettify Symbols Mode is not a package whose purpose—according to its
name—is completion.

At least I'd like to have an official way to get just the Company part and
the key bindings but not the various other things.  Probably you could
split company-coq-initialise into a set of individual minor modes which
could be enabled individually.

Am Sonntag, 24. Mai 2015 schrieb Clément Pit--Claudel :

**Comment by cpitclaudel** [comment]
> It would, but for this approach I'd much prefer a company-coq-initialize-hook which is guaranteed to run after company coq initialisation. That's just less brittle than relying on the order of functions in a single hook

What about this then?
```
(defun my-company-coq-initialize ()
  (company-coq-initialize)
  (show-paren-mode -1)
  (prettify-symbols-mode -1))
(add-hook 'coq-mode-hook #'my-company-coq-initialize)
```

Adding a hook would probably be easy. Feel free to make a pull request. I'll probably do it in the next week or so otherwise.

> But generally I think that a package should not encode personal preferences of its maintainers an developers. IOW I think the proper place for Prettify Symbols Mode is not a package whose purpose—according to its name—is completion.

The name is indeed outdated; the package grew beyond its initial purpose. I'm not aware of a way to change that name now. Regarding whether prettify is relevant: it's pretty common for IDE-style packages to encode such subjective preferences. Proof General already does it; so does elpy. It makes beginner's life easier, at the cost of a small inconvenience to more experienced users.

>  At least I'd like to have an official way to get just the Company part and the key bindings but not the various other things.

The `company-coq-initialize` function is very straightforward, and minor mode initialization is already in a separate function that it calls. Fell free to add an `defcustom` to disable minor modes and make a PR. Otherwise I'll probably do it, too.

> Probably you could split company-coq-initialise into a set of individual minor modes which could be enabled individually.

Note that the definition of that function has a comment that reads:

```
;; TODO this could be a minor mode
```

I'll take relevant PRs :)

**Comment by lunaryorn** [comment]
@cpitclaudel Shame on me, I didn't even think of using my own function :flushed: 

Still, I'd prefer if I could just pick Company support from this package, and nothing else.   If that's impossible, the name of this package is misleading at the very least.

I'm not aware of any difficulties in renaming a package.  Isn't it just a matter of renaming the repo, the package files, and submitting a PR on MELPA?  On the other hand, why not keep the name, but for the Company part only, and move all the rest into a separate package, e.g. coq-ide or elcoq (after elpy)?

I know that elpy and similar packages exist, but the difference between this package and elpy is that all the ingredients of elpy are available independently or implemented by alternative packages with less opinions (e.g. Anaconda Mode).  The ingredients of this package are not.

ProofGeneral is another story, but it's also poorly written, breaks many Emacs conventions, and is generally not a particularly good Emacs citizen.  IOW, PG is not a good package, it's just the only one in its niche.  It's not a package that one should follow.

**Comment by cpitclaudel** [comment]
I'll reopen this one actually :) I've experimented with better feature segmentation when writing my F* mode, so I feel that I have a better understanding of how this could be improved now. I've been busy migrating Proof General to git of late (https://github.com/ProofGeneral/PG !), but I'm hoping to work on this next week-end.

WRT renaming: it probably wouldn't be too hard; I'm a bit afraid of creating more confusion than already exists. Some of the features in company-coq will ultimately be merged in PG, and once there's a clearer picture of where the boundary falls between the two packages it'll be easier to rename it if needed :)

**Comment by lunaryorn** [comment]
@cpitclaudel Ah, great news.  I don't get to do a lot of Coq of late, but when I'm back to it, I'm dead sure I'll absolutely enjoy your work on this package.  Migrating Coq to Git is great news, it was long overdue.  The CVS repo was a nuisance!  Keep up the great work :heart_eyes: 

PS: Where can I donate? :)

**Comment by cpitclaudel** [comment]
Alright, it's been a while, but I eventually got to work on this refactoring! 

Company-coq is now (well, on the `massive-cleanup` branch at least) composed of a collection of 22 relatively independent "features" (they are essentially like simple minor modes), which all come with setup and teardown code. 

`pg-improvements` (which includes `show-paren-mode`), and `prettify-symbols` (which sets up `prettify-symbols-mode`) are two such features; the customize interface for `company-coq-disabled-features` makes it trivial to disable them.

I also took the opportunity to convert `company-coq` to a minor mode, so it now has a clean hook :) More generally, the code looks much cleaner and much more clear now with this separation into smaller features (it helps as well that I forced myself to document all of it).

**Comment by cpitclaudel** [comment]
About changing the name: I considered for a while, but I'm wasn't sure of how well the migration would work for existing users — nor whether it was worth the trouble, so I didn't end up renaming. (More generally, I hope at some point in the future to merge back significant parts of comany-coq into Proof-General, keeping the focus on company in company-coq; and finally I'm going to give a talk about this at CoqPL in January under the name `company-coq`, so I didn't want to add confusion).

**Comment by lunaryorn** [comment]
@cpitclaudel Awesome work :heart_eyes:  :fireworks:
