### ISSUE TITLE
Coq Goals window won't update if goto the point after comments

### ISSUE THREAD

**Issue by LukeXuan** [cpitclaudel/company-coq#161]
Hi, If I use `proof-goto-point` when the cursor is located at some comments or after some comments, the Goal window is unchanged. Is this a bug of company-coq of it should be reported to proof general?

**Comment by cpitclaudel** [comment]
Does it still happen if you turn off company-coq ? If so, it's a PG bug :)

**Comment by LukeXuan** [comment]
reported to https://github.com/ProofGeneral/PG/issues/204, closing this one
