### ISSUE TITLE
company-coq does not work with debian/ubuntu 16.04's emacs 

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#166]
I can no longer install company-coq:
```
Compiling file /home/jgross/.emacs.d/elpa/company-coq-20170504.1519/company-coq.el at Wed May 17 15:49:24 2017
company-coq.el:82:1:Error: Symbol's function definition is void: cl-struct-define
```
This is with GNU Emacs 24.5.1

**Comment by cpitclaudel** [comment]
Please see https://emacs.stackexchange.com/questions/19658/cant-use-magit-in-spacemacs-symbols-function-is-void-cl-struct-define , https://github.com/syl20bnr/spacemacs/issues/3129, or https://github.com/magit/magit/issues/1838 ; you're trying to load files compiled by Emacs 25 into Emacs 24.5.

**Comment by JasonGross** [comment]
Ah, thanks!
