### ISSUE TITLE
parsing fails in Coq trunk

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#168]
```
company-coq: Parsing of tactic grammar failed with error (error "Top level parsing failure [(1 subgoal (ID 61206) Name : Type InterpC\
ontext : Context Name interp_base_type InterpContextOk : ContextOk InterpContext Name_beq : Name -> Name -> bool Name_bl : forall n1 \
n2 : Name (, Name_beq) n1 n2 = true -> n1 = n2 Name_lb : forall n1 n2 : Name (, n1) = n2 -> Name_beq n1 n2 = true i1 (, i3) : Name tC\
 : flat_type base_type e2_2_2 : exprf tC ctx : InterpContext v : interp_flat_type interp_base_type tC z0 : Z n (, n0) (, n1) : Name e\
1 : exprf (tZ * tZ) f : flat_type base_type o : op f (tZ * tZ) e : exprf (tZ * tZ * tZ) e0 : exprf (tZ * tZ) e4 : exprf tZ f0 : flat_\
type base_type o0 : op f0 tZ e6 : exprf)]").
```
This is either a bug in Coq trunk that @ejgallego should fix, involving which commands print the goal after they're run (or else involving `Set Silent`), or else it's a bug in company-coq in assuming that the goal won't get printed after certain commands (which was true in 8.6, but is false in trunk)

**Comment by cpitclaudel** [comment]
Thanks for the report. Does trunk print the goal after the output of `Print Grammar`?

**Comment by JasonGross** [comment]
No, it doesn't seem to (at least not after `Print Grammar constr`).  However, it does print out the goal after `Timeout 1 Print Grammar constr`.

**Comment by JasonGross** [comment]
Reported as [bug #5537](https://coq.inria.fr/bugs/show_bug.cgi?id=5537).

**Comment by ejgallego** [comment]
Wouldn't it be easier if coq never printed the goals in `-emacs` mode?

**Comment by ejgallego** [comment]
By the way this is fixed by coq/coq#640

**Comment by cpitclaudel** [comment]
@ejgallego I'm not sure. Changes are always harder to accommodate than no changes :)

**Comment by psteckler** [comment]
@JasonGross I was getting the same "Parsing of tactic grammar" error with company-coq; I think the upgrade to the latest MELPA version got rid of it.

**Comment by Blaisorblade** [comment]
FWIW I get similar "Parsing of tactic grammar" failures with Coq 8.6:
```
company-coq: Parsing of tactic grammar failed with error (error "Tactic parsing failure [(INT 3)]").
```

**Comment by cpitclaudel** [comment]
@Blaisorblade were you using an up-to-date company-coq?

**Comment by Blaisorblade** [comment]
@cpitclaudel Not sure, but please ignore. Can’t reproduce any more on up-to-date Spacemacs and Coq 8.6.1 (not sure which one was responsible), and the offending computer is dead.

**Comment by cpitclaudel** [comment]
Thanks. Closing this; feel free to reopen if it happens again.
