### ISSUE TITLE
'nat' is shown as [

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#19]
Using GNU FreeMono font in AquaMacs instead of 'nat' is shown as [.
I also tried several other fonts.

![screenshot 2015-06-25 11 59 52](https://cloud.githubusercontent.com/assets/86581/8363149/0eb73c42-1b32-11e5-8ac7-79fd44d71106.png)

Other math symbols like arrows and quantifiers are shown correctly.

**Comment by cpitclaudel** [comment]
This screenshot is definitely not showing FreeMono, but anyway here's my guess: you have a broken font on your system that claims to have "𝓝", but renders it as "[".

That's easily fixed (copying from the README): use

```elisp
(set-fontset-font t 'unicode (font-spec :name "Symbola") nil 'append)
```

Or FreeSerif, or STIX

**Comment by vzaliva** [comment]
tried `set-fontset-font` with FreeSerif as I do not have STIX or Symbola fonts installed. It did not help.
I verified again with FreeMono and FreeSerif and I can confirm that screen font indeed change, but natural numbers are now shown with question mark. Attaching more screenshots using FreeMono and FreeSerif:

![screenshot 2015-06-25 15 43 57](https://cloud.githubusercontent.com/assets/86581/8367260/5674abb8-1b51-11e5-8627-8b18a0d3fe2a.png)
![screenshot 2015-06-25 15 44 09](https://cloud.githubusercontent.com/assets/86581/8367261/5676b2e6-1b51-11e5-8b08-3f1822903a41.png)

**Comment by cpitclaudel** [comment]
For the record: Vadim and I talked about and tried to fix it, but we didn't really find a solution (Emacs doesn't seem to be finding the right fonts). 

In that case, the easiest workaround after trying a font like [Symbola](http://users.teilar.gr/~g1951d/Symbola.zip) (short of disabling prettification entirely) is to remove these two particular symbols from the prettification table (<kbd>M-x customize-variable RET company-coq-prettify-symbols-alist RET</kbd>).

**Comment by cpitclaudel** [comment]
I've trying to debug issues with Aquamacs recently (I had access to a mac), and the following worked for me:

* Install Symbola from http://users.teilar.gr/%7Eg1951d/Symbola.zip
* Add the following to your `.emacs`:

```elisp
(dolist (ft (fontset-list))
  (set-fontset-font ft 'unicode (font-spec :name "Monaco"))
  (set-fontset-font ft 'unicode (font-spec :name "Symbola") nil 'append))
```

Do you think you could give it a try?

**Comment by vzaliva** [comment]
I tried that. "bool" is show as opening square bracket:

<img width="199" alt="screenshot 2016-01-26 14 24 24" src="https://cloud.githubusercontent.com/assets/86581/12597199/c68a3130-c438-11e5-8fb3-439f8a232dfe.png">

M-x describe-char shows:

<img width="548" alt="screenshot 2016-01-26 14 25 26" src="https://cloud.githubusercontent.com/assets/86581/12597200/c68c09e2-c438-11e5-802c-dfc8c5875909.png">

**Comment by vzaliva** [comment]
But "nat" is shown correctly. See 'describe-char' info for it. I see that unlike "bool" it uses Symbola.

<img width="552" alt="screenshot 2016-01-26 14 28 21" src="https://cloud.githubusercontent.com/assets/86581/12597278/2cff2a24-c439-11e5-8bcd-df40112ff79d.png">

**Comment by cpitclaudel** [comment]
Oh well. I really don't know what could be causing this. I tried on a mac, and I had no issues with Aquamacs, nor with the official Emacs at http://emacsformacosx.com/, nor with the Emacs Mac port at https://github.com/railwaycat/homebrew-emacsmacport/releases.

Is there a reason why you're using Aquamacs instead of one of the other two?

**Comment by vzaliva** [comment]
Auqamacs has good integration with native Mac windowing system and OS-level keyboard shortcuts, etc. It is a popular Emacs choice amongst Mac users.

I will try to figure out the problem on my own. For some reason for 'bool' symbol incorrect font is used. Interestingly, for 'nat' the correct phone is used, as shown above. I do not know yet how font selection mechanism works, but I will try to figure out.

Feel free to assign ticket to me.

**Comment by cpitclaudel** [comment]
Thanks a lot; that's really helpful :)

**Comment by vzaliva** [comment]
I have spent some time experimenting with this issue, and apparently the problem is with Symbola font. Even when I copy-past math "B" character to Aquamacs buffer it is not shown correctly. The good news that default font works correctly.

<img width="585" alt="screenshot 2016-02-01 15 18 33" src="https://cloud.githubusercontent.com/assets/86581/12735025/55c0fa18-c8f9-11e5-973b-bb046cb8c1a6.png">
