### ISSUE TITLE
Overeager completion

### ISSUE THREAD

**Issue by joelburget** [cpitclaudel/company-coq#190]
Completion triggers even after I've moved on from a word. Example where I hit <kbd>esc</kbd> at the end.

![complete](https://user-images.githubusercontent.com/310981/34911316-1841b87a-f87d-11e7-9f8d-40ecc777edbb.gif)

Since I have a lot of `t`s in my development, they all tend to end up as `trivial`s...

From experimenting it seems to be the case that this doesn't happen if another autocomplete has been triggered before hitting <kbd>esc</kbd>.

**Comment by cpitclaudel** [comment]
Duplicate of https://github.com/cpitclaudel/company-coq/issues/174 maybe?

**Comment by joelburget** [comment]
Sure was. Thanks!
