### ISSUE TITLE
Module include highlighted as syntax error

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#192]
In the following example:

``Module Type A.
   Include B.
   ...
```
Include line is highlighted as an error.

Not sure if it is company-coq or PG bug. Please advise.

**Comment by cpitclaudel** [comment]
What do you mean by "highlighted as an error"?  (a screenshot would help)

**Comment by vzaliva** [comment]
I am sorry, I just tried to reproduce it to take a screenshot and it does not repeat!
What happened there was a red line under "Include B". Not sure what it means.
Sorry, maybe I was too quick to report. I will try to get a better reproducible case next time.
