### ISSUE TITLE
How to disable the automatic insertion of unicode symbols?

### ISSUE THREAD

**Issue by tsktsktsk64** [cpitclaudel/company-coq#193]
Hi there,
I've been using company-coq for a while now and it has been great. Just one problem: I don't want the feature of inserting Unicode symbols, `\beta` for example (because the font I use lack many of the symbols and the slow fallback system of Emacs hangs a few seconds every time I type `\` and a character). So I'm wondering if I can just disable it? I checked `customize` and saw an option of disabling separate parts of company-coq, but not this one.
Thanks!

**Comment by cpitclaudel** [comment]
You want to disable this one, I think:

```
[ ] Completion of LaTeX macros.
     Inserts ⊕ when you type oplus.
```

Upgrading your Emacs should also fix the slow fallback issue.

**Comment by tsktsktsk64** [comment]
@cpitclaudel I actually solved the problem by using your monospacifier so now I don't have to disable that great feature any more! Thanks Clément!
