### ISSUE TITLE
Disable completion for `false`?

### ISSUE THREAD

**Issue by liyishuai** [cpitclaudel/company-coq#196]
When I type `false RET`, I always get a `false_hyp H G`.
How can I disable this feature and get `false\n` without using `false SPC DEL RET`?

**Comment by liyishuai** [comment]
Solved partially by customizing `company-coq-disabled-features`:

| If you don't want to autocomplete ... | into... | , then disable ... |
|---------------------------------------|-----------------------------------------------------|---------------------------------|
| `false` | `false_hyp H G` | `dynamic-tactics-backend` |
| `str` | `string_scope` | `refman-scope-abbrevs-backend` |
| `str` | `setoid_replace term with term using relation term` | `refman-tactic-abbrevs-backend` |

These autocompletions are both useful and annoying. Can we have a more flexible configuration *e.g.* customized dictionary of regexps that escape autocompletion?

**Comment by cpitclaudel** [comment]
Thanks. The issue with `false` is fairly easy to fix (it just needs to be in this function:)

```elisp
(defun company-coq--reserved-keywords-regexp ()
  "Construct and cache a regexp matching Coq's reserved keywords."
  (or company-coq--reserved-keywords-regexp
      (setq company-coq--reserved-keywords-regexp
            (concat "^" (regexp-opt (append coq-reserved '("Set" "Prop" "Type"))) "$"))))
```

str is trickier.  Did you consider rebinding RET, to prevent it from triggering completion?

**Comment by cpitclaudel** [comment]
The customized list of regexp is possibly a good idea, but I think it's a generic company-mode issue.  The one thing you might consider as a workaround is to change company-idle-delay to a larger value than the one currently set by company-coq.

**Comment by liyishuai** [comment]
How to config emacs to enable the fix you mentioned in `company-coq--reserved-keywords-regexp`?
