### ISSUE TITLE
YASnippet dependency

### ISSUE THREAD

**Issue by lunaryorn** [cpitclaudel/company-coq#2]
Hello,

is there a chance to make the YASnippet dependency optional?  I'd love to use Company in Coq buffers, but I don't use YASnippet at all.

**Comment by cpitclaudel** [comment]
Hi,

Most of the package's functionality relies on Yasnippet ­­— especially the parts that directly relate to company. Would you rather the templates use Holes (which already ships with Proof-General)? Or do you have an other idea of how we could get useful company support without yas?

If/Once Coq gets the SearchMinimal patch, making it possible to print all defined identifiers (see  https://github.com/cpitclaudel/company-coq/blob/master/img/symbol-completion.png), then a significant chunk of company-coq won't depend on Yasnippet; in the meantime, though, I'm not sure what the best approach is except for requiring Yasnippet.

**Comment by cpitclaudel** [comment]
Side note: do you see any downsides to depending on Yasnippet apart from the additional download?

**Comment by lunaryorn** [comment]
@cpitclaudel No, I don't see any downsides, not even the additional download—I already have 100 packages installed, one more or less doesn't matter anymore.

I was just curious about why a snippet package is a dependency of a company backend.

Thanks for your quick reply, and for your great work on this package!
