### ISSUE TITLE
How do I add multi-character replacements to prettify-symbols-alist?

### ISSUE THREAD

**Issue by anton-trunov** [cpitclaudel/company-coq#201]
I'd like `[**` to be rendered as `[△`.

What would be the correct way of adding something like `("[**"  . "[△")` to `prettify-symbols-alist`? I don't want `**` to be rendered as `△` in all contexts.

**Comment by cpitclaudel** [comment]
It's tricky.  There are multiple ways to do this:

* Use a font-lock rule with a display property (that is, don't use prettify-symbols-mode directly)
* Use a composition string.  It's documented in the docstring of compose-region and reference-point-alist, which are a bit complex.  The relevant part is this:

```
If it is a vector or list, it is a sequence of alternate characters and
composition rules, where (2N)th elements are characters and (2N+1)th
elements are composition rules to specify how to compose (2N+2)th
elements with previously composed N glyphs.
```

So you want this: `(setq prettify-symbols-alist '(("[**" . (?\[ (Br . Bl) ?△))))`.  See https://emacs.stackexchange.com/questions/34808/using-prettify-symbols-with-strings-instead-of-characters

**Comment by anton-trunov** [comment]
Wow! It works. Thank you very much!

Do you think it is worth adding your example to `README.md`? For instance, to this [this section](https://github.com/cpitclaudel/company-coq#for-a-single-project)?

**Comment by cpitclaudel** [comment]
I think a brief link to this issue would be perfect, yes. Can you prepare a PR? :)
