### ISSUE TITLE
Newline without auto-indentation

### ISSUE THREAD

**Issue by pseudohuman92** [cpitclaudel/company-coq#206]
Can you make <shift>+<enter> to create a new line without auto-indenting the previous line and starting new line at the same position with the previous line.

**Comment by cpitclaudel** [comment]
I don't really understand the request, but you can certainly rebind `RET` to any command you want :)

**Comment by cpitclaudel** [comment]
Turns out the issue is with `electric-indent-mode`

**Comment by cpitclaudel** [comment]
See http://emacsredux.com/blog/2013/03/29/automatic-electric-indentation/ for details on how to tweak it :)
