### ISSUE TITLE
`M-.` error

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#213]
Pressing `M-.` switches to the buffer where the definition is but does not position the line. The erro is shown:

```
company-coq-scroll-above-definition-at-pt: Symbol’s function definition is void: coq-looking-at-comment [2 times]
```

(Using latest MELPA version)

**Comment by vzaliva** [comment]
I looked at it further. Based on the following declaration:

```
(company-coq-forward-declare-fun coq-looking-at-comment "ext:coq-indent.el" cmd)
```

It must be defined in ProofGeneral's `coq-indent.el`. In PG version 20190212.1433 (from ELPA) it is commented out:

```
;; (defun coq-looking-at-comment ()
;;   "Return non-nil if point is inside a comment."
;;   (or (proof-inside-comment (point))
;;       (proof-inside-comment (+ 1 (point)))))
```

I am not sure how to fix it. :)

**Comment by vzaliva** [comment]
@cpitclaudel

**Comment by cpitclaudel** [comment]
Thanks for the ping.  The problem was introduced by @monnier in https://github.com/ProofGeneral/PG/commit/fb3b75dab55b6e6befffc53e136422558be5faa0
We should just import this exact definition (with a different name) into company-coq.

**Comment by monnier** [comment]
We could also uncomment Proof-General's definition and mark it obsolete
(with a comment explaining that PG doesn't use it any more but some
rogue external abusers are still out in the wild).

**Comment by cpitclaudel** [comment]
> rogue external abusers

Hey, that function didn't have a double-dash ^^
I think just moving it to company-coq is fine. @vzaliva, do you want to prepare a patch?

**Comment by vzaliva** [comment]
@cpitclaudel I can try. I recall you've showed me some mechanism you use to switch between dev. and official versions of emacs packages you use for development. Could you remind me please what was it?

**Comment by vzaliva** [comment]
Found it. It was `cask`. Still figuring out how to use it. After installing `cask` running make fails:

```
env --unset INSIDE_EMACS EMACS=emacs cask clean-elc
env --unset INSIDE_EMACS EMACS=emacs cask pkg-file
env --unset INSIDE_EMACS EMACS=emacs cask package
env --unset INSIDE_EMACS EMACS=emacs cask build
Compiling /home/lord/lisp/company-coq/company-coq-abbrev.el...
Compiling /home/lord/lisp/company-coq/company-coq-pkg.el...
Compiling /home/lord/lisp/company-coq/company-coq-tg.el...
Compiling /home/lord/lisp/company-coq/company-coq-utils.el...
Compiling /home/lord/lisp/company-coq/company-coq.el...

In toplevel form:
company-coq.el:73:1:Error: Cannot open load file: No such file or directory, company
```

I have `company` installed via MELPA in my emacs.

**Comment by vzaliva** [comment]
pull request submitted.

**Comment by vzaliva** [comment]
@cpitclaudel it is a nasty bug affecting the core functionality, something people use many times per day when working in PG. I recommend pushing the MELPA update as soon as possible.

**Comment by cpitclaudel** [comment]
Thanks for the ping.
