### ISSUE TITLE
symbol prettification and smart subscripts become enabled despite setting upon opening second coq buffer

### ISSUE THREAD

**Issue by ingvar-lynn** [cpitclaudel/company-coq#219]
Current settings:
```
(add-hook 'company-coq-mode-hook (lambda ()
            (prettify-symbols-mode -1)
            (company-coq-features/smart-subscripts--disable)
            ))

(add-hook 'coq-mode-hook (lambda () 
   (company-coq-mode)
...
```

So when I open say A.v everything behaves as expected. Then I open B.v in another buffer and symbols in the first buffer become prettified but B.v is displayed correctly.

company-coq version: 20190412.317

**Comment by cpitclaudel** [comment]
Yes, that's not ideal but I think it's 'by design'.  Instead of adding a company-coq hook to disable some features, the best would be to customize company-coq-disabled-features. Can you try that?

**Comment by ingvar-lynn** [comment]
Customizing company-coq-disabled-features indeed solved the issue.
I've tried that before but did not succeed for some reason.
Great extension btw!
