### ISSUE TITLE
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: number-or-marker-p, nil" on command post-command

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#22]
![screenshot from 2015-09-05 14 08 04](https://cloud.githubusercontent.com/assets/396076/9700627/a4eb6912-53d7-11e5-9973-d29ccaf52a0d.png)

After updating all of my emacs packages just now, I pasted the code at the bottom into a fresh emacs buffer `/tmp/foo5.v` (with the Edit->Paste terminal menu), and then pressed the down arrow key while emacs was pasting.  This is emacs inside ssh inside screen inside ssh.  Holding down `C-g` killed it after a while.

Is it possible to make company-coq not try to do anything complicated while pasting code?

Pasted code:
```coq
Require Coq.Lists.List.
Global Set Implicit Arguments.
Import Coq.Lists.List.
Class IndexBound {A : Set} (a : A) (Bound : list A) :=
  { ibound :> nat;
    boundi : nth_error Bound ibound = Some a}.
Global Arguments ibound {A} [a Bound] _ .
Global Arguments boundi {A} [a Bound] _.
Record BoundedIndex {A : Set} (Bound : list A) :=
  { bindex : A;
    indexb :> IndexBound bindex Bound }.

Context {A : Type} {C : Set}.
Variable (projAC : A -> C).
Axiom None_neq_Some : forall (AnyT AnyT' : Type) (a : AnyT), None = Some a -> AnyT'.

Definition nth_Bounded'
           (Bound : list A)
           (c : C)
           (a_opt : option A)
           (nth_n : option_map projAC a_opt = Some c)
: A := match a_opt as x
             return (option_map projAC x = Some c) -> A with
         | Some a => fun _ => a
         | None => fun f => None_neq_Some _ f
       end nth_n.

Axiom nth_error_map : forall n As c_opt, nth_error (map projAC As) n = c_opt -> option_map projAC (nth_error As n) = c_opt.

Definition nth_Bounded
           (Bound : list A)
           (idx : BoundedIndex (map projAC Bound))
: A := nth_Bounded' Bound (nth_error Bound (ibound idx))
                    (nth_error_map _ _ (boundi idx)).

Program Definition nth_Bounded_ind2
        (P : forall As, BoundedIndex (map projAC As)
                        -> BoundedIndex (map projAC As)
                        -> A -> A -> Prop)
: forall (Bound : list A)
         (idx : BoundedIndex (map projAC Bound))
         (idx' : BoundedIndex (map projAC Bound)),
    match nth_error Bound (ibound idx), nth_error Bound (ibound idx') with
      | Some a, Some a' => P Bound idx idx' a a'
      | _, _ => True
    end
    -> P Bound idx idx' (nth_Bounded _ idx) (nth_Bounded _ idx'):=
  fun Bound idx idx' =>
    match (nth_error Bound (ibound idx)) as e, (nth_error Bound (ibound idx')) as e'
          return
          (forall (f : option_map _ e = Some (bindex idx))
                  (f' : option_map _ e' = Some (bindex idx')),
             (match e, e' with
                | Some a, Some a' => P Bound idx idx' a a'
                | _, _ => True
              end)
             -> P Bound idx idx'
                  (match e as e'' return
                         option_map _ e'' = Some (bindex idx)
                         -> A
                   with
                     | Some a => fun _ => a
                     | _ => fun f => _
                   end f)
                  (match e' as e'' return
                         option_map _ e'' = Some (bindex idx')
                         -> A
                   with
                     | Some a => fun _ => a
                     | _ => fun f => _
                   end f')) with
      | Some a, Some a' => fun _ _ H => _
      | _, _ => fun f => _
    end (nth_error_map _ _ (boundi idx))
        (nth_error_map _ _ (boundi idx')).

Lemma nth_Bounded_eq
: forall (Bound : list A)
         (idx idx' : BoundedIndex (map projAC Bound)),
    ibound idx = ibound idx'
    -> nth_Bounded Bound idx = nth_Bounded Bound idx'.
Proof.
  intros.
  eapply nth_Bounded_ind2 with (idx := idx) (idx' := idx').
  simpl.
  pattern (nth_error Bound (ibound idx')); case_eq (nth_error Bound (ibound idx')) || fail "too early".
  Undo.
  unfold Exc; case_eq (nth_error Bound (ibound idx')) || fail "too early".
  Undo.
  case_eq (nth_error Bound (ibound idx')).
```

If I spam `C-g`, it seems to consistently end up at `    -> P Bou` in `Program Definition nth_Bounded_ind2`.

**Comment by cpitclaudel** [comment]
Hi Jason,

Thanks for the report. This seems to be due to company itself, not company-coq; the post-command hook is something that runs just once after every command. Did it freeze emacs in addition to showing that message? And can you reproduce that bug?

Also, which version of PG are you using? CVS?

Cheers,
Clément.

**Comment by JasonGross** [comment]
The bug is consistently reproducible the 2-3 times that I tried it (and I just tried again now, though I had to wait about 20 seconds before it showed up).  It shows that error message repeatedly (it keeps flashing between that, and something else I can't read).  It "freezes" emacs in the sense that I can't switch to another file, but if I spam `C-g` enough, it stops, and the text up to `-> P Bou` shows up, and then I can do other things.  I'm using PG 4.3pre131011.

**Comment by cpitclaudel** [comment]
That sounds like an old version of PG (older than the current, already outdated development release?). Could you try `toggle-debug-on-quit` before reproducing the bug? Then pressing Ctrl+G during the loop should cause a backtrace to be printed.

**Comment by JasonGross** [comment]
Note that I have to *spam* Ctrl+g to get it to abort, not just press it once.  Doing toggle-debug-on-quit (so it says that it's enabled globally) doesn't seem to give me a backtrace.  `*Messages*` is still filled with a few dozen repetitions of
```
Company: An error occurred in post-command
Company: Front-end company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: number-or-marker-p, nil" on command post-command
```
followed at the bottom by
```
Quit
Auto-saving...
Quit [10 times]
```

Ah, okay, by being more careful with Ctrl-g, I got a debug trace, but it doesn't seem very helpful:
![screenshot from 2015-09-05 16 28 48](https://cloud.githubusercontent.com/assets/396076/9701153/45a7202c-53eb-11e5-9e3e-65425ddab21f.png)

**Comment by JasonGross** [comment]
Should I update PG and see if that makes it go away?

**Comment by cpitclaudel** [comment]
This is a very disappointing backtrace indeed. Updating could help, but one would hope that PG wouldn't interfere with company :/

**Comment by cpitclaudel** [comment]
@JasonGross, can you reproduce still this? 

My guess would be that this is connected to pastes being handled by the terminal as a series of individual keypresses, instead of a block paste. Emacs 25 will have support for bracketed paste, which handles pasting the right way; otherwise, there's a bracketed-paste package on the wiki.

**Comment by JasonGross** [comment]
I updated PG and company (and my other packages) to the latest version, and it's still there, with PG 4.3pre150930, GNU Emacs 24.3.1.  The lack of bracketed paste does indeed exacerbate the problem, but it still seems like a bug.  We could debug this in person sometime, if you want.

I also managed to get
```
$ fg
emacs foo.v
Garbage collection in progress; cannot auto-save now
but will instead do a real quit after garbage collection ends
Abort (and dump core)? (y or n)
```
by pressing `C-z` and then spamming `C-g`.

**Comment by cpitclaudel** [comment]
Ok, let's look at it together when I come back :) Thanks a lot for your help!

By the way (though I don't think it'll make a difference here), you'll be much better off using Proof General from https://github.com/ProofGeneral/PG than from the website :)

**Comment by cpitclaudel** [comment]
I've reproduced this; I can also confirm that bracketed paste in Emacs25 fixes it. 
I'm going to bet that this is caused by https://github.com/company-mode/company-mode/issues/455.
