### ISSUE TITLE
How can i stop auto-completion of points?

### ISSUE THREAD

**Issue by DingossC** [cpitclaudel/company-coq#228]
When using company coq auto-completion with electric terminator mode of proof general, the auto-completion of points turns a bit annoying, due that to being able to process the next step i need to erase the point and write it again.

**Comment by cpitclaudel** [comment]
Can you clarify what you mean by autocompletion of points?

**Comment by DingossC** [comment]
Example: When i type Che, and auto-complete with Check _term_**.** This write a point that i have to erase and type again to run the next command, i wish to be able to use auto-completion but without points. Sorry if i wasn't clear enough.

**Comment by cpitclaudel** [comment]
Ah, got it.
It's not very easy to do at the moment.  This works, I think:

```elisp
(defun my/company-coq-remove-final-dot (args)
  "Remove final dot of abbrev in ARGS."
  (pcase args
    (`((,abbrev . ,anchor))
     (let* ((lastpos (1- (length abbrev))))
       (if (and (>= lastpos 0) (= (aref abbrev lastpos) ?.))
           `((,(substring abbrev 0 lastpos) . ,anchor))
         args)))))

(advice-add #'company-coq-parse-man-db-entry
            :filter-args #'my/company-coq-remove-final-dot)
```

Please try it and let me know.

**Comment by DingossC** [comment]
Yes, it works. Thank you :D
