### ISSUE TITLE
\square not included?

### ISSUE THREAD

**Issue by beta-ziliani** [cpitclaudel/company-coq#232]
the auto-completion of symbols lists 17 squares (\squarelrquad, ...) but no \square. while at it, where do I get the list of symbols supported?

**Comment by cpitclaudel** [comment]
That list of symbols comes from https://github.com/vspinu/math-symbol-lists/blob/master/math-symbol-lists.el; surprisingly, it does contain square, so I'd be inclined to blame a `company-math` (which is responsible for the completion).

`\mdwhtsquare` works

**Comment by beta-ziliani** [comment]
maybe the lists from amssymb and misc are not in company-coq?

**Comment by beta-ziliani** [comment]
(note that square is there under amssymb)

**Comment by beta-ziliani** [comment]
ok, I replicated the issue there, will close this one

**Comment by beta-ziliani** [comment]
FTR, solved [there](https://github.com/vspinu/math-symbol-lists/issues/7).
