### ISSUE TITLE
company-coq won't install from melpa

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#237]
With PG already installed, using Emacs 26.3 in Lubuntu, M-x package-install RET company-coq RET gives this:

Contacting host: melpa.org:443
package-install-from-archive: https://melpa.org/packages/dash-20191109.1327.tar: Not found

**Comment by cpitclaudel** [comment]
M-x package-refresh-contents?

**Comment by jonleivent** [comment]
Of course.

**Comment by cpitclaudel** [comment]
Really? Normally the error you've seen is just an outdated package index, and refreshing fixes it. Can you try list-packages ? What version of dash does that show?

**Comment by jonleivent** [comment]
I meant that package-refresh-contents fixed it, and I should have thought of it myself especially considering the date tag on that dash tar.  Sorry for the ambiguity.  If you had seen me face-palm, it would have been clearer ;)  Thanks.

**Comment by cpitclaudel** [comment]
Ah, super :) Thanks for clarifying!
