### ISSUE TITLE
No match when installing this package from MELPA

### ISSUE THREAD

**Issue by PalindromeLeung** [cpitclaudel/company-coq#240]
I followed the instructions in the README.md file and copied the setting for the `.emacs` file. After refreshing the packages, Emacs complains that there's no match for `company-coq`. Even if I listed all the available packages from MELPA, it wasn't there. Does it require specific versions of Emacs, Coq, and Proof General?

**Comment by cpitclaudel** [comment]
> Does it require specific versions of Emacs

Yes, but your Emacs is likely recent enough.

> After refreshing the packages, Emacs complains that there's no match for company-coq

Do you see other MELPA packages in `M-x list-packages` ? If not, try `M-x package-refresh-contents` (I see it at https://melpa.org/#/company-coq , so it's likely a configuration issue that's not directly to company-coq, but of course I'm happy to help)

**Comment by PalindromeLeung** [comment]
Yeah, my emacs version is 26.3(9.0). It's there in the list when `M-x list-packages` but I'm not able to install it via `M-x package-install` after `M-x package-refresh-contents`.

**Comment by cpitclaudel** [comment]
Sounds like it's already installed?

**Comment by PalindromeLeung** [comment]
Très bien! It's there already. Still this feels weird.
