### ISSUE TITLE
broken Layout  when using Tex

### ISSUE THREAD

**Issue by gaxiiiiiiiiiiii** [cpitclaudel/company-coq#243]
when changing LaTex comand to Unicode symbol, Layout is broken.

here, layout  is good.
<img width="369" alt="スクリーンショット 2020-08-05 10 46 32" src="https://user-images.githubusercontent.com/17435600/89362663-63f68800-d709-11ea-8517-06be31eee0ff.png">

after put enter, layout is broken. '∈' and ')' are overlapping.
<img width="242" alt="スクリーンショット 2020-08-05 10 46 40" src="https://user-images.githubusercontent.com/17435600/89362718-8d171880-d709-11ea-9f9a-73e623988b57.png">

after put space, new  ')' appears.
<img width="242" alt="スクリーンショット 2020-08-05 10 47 42" src="https://user-images.githubusercontent.com/17435600/89363356-ed5a8a00-d70a-11ea-8c58-017d261ec7e4.png">

after Execution, layout is good.
<img width="308" alt="スクリーンショット 2020-08-05 10 48 38" src="https://user-images.githubusercontent.com/17435600/89362959-0f9fd800-d70a-11ea-87b3-19548f0236d2.png">

**Comment by cpitclaudel** [comment]
This is a font issue, either from Emacs or from your terminal emulator (are you running an X Emacs or a command line one?).  The problem isn't specific to company-coq, so you'd likely want to report it either to the Emacs folks or to the developer of your terminal emulator.  Practically speaking though, your best bet is probably to install a monospace font that supports these characters (consider Fira Code or DejaVu Sans Mono), which should solve the issue.
