### ISSUE TITLE
New subscript syntax?

### ISSUE THREAD

**Issue by liyishuai** [cpitclaudel/company-coq#246]
I enjoyed the subscript syntax in company-coq, until triggering tons of warnings during extraction:
```coq
Definition a__b := tt.
From Coq Require Import Extraction.
Extraction a__b.
```
> Warning: The identifier a__b contains __ which is reserved for the extraction
[extraction-reserved-identifier,extraction]

Is it worth deprecating the current syntax in favour of some other one?

**Comment by cpitclaudel** [comment]
Related issues https://github.com/coq/coq/issues/5397 , https://github.com/antalsz/hs-to-coq/issues/88 ; I think that's an issue that should be fixed in Coq.

**Comment by liyishuai** [comment]
Yes it makes more sense to fix in Coq.
