### ISSUE TITLE
company-coq-go-to-point fails

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#248]
Pressing `C-c` `<C-return>` gives error: "apply: Wrong number of arguments: (0 . 0), 1".
Company-Coq version: 20210417.2329 (latest from melpa)
PG version:  Version: 20210408.1454 (latest from melpa)
GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-03-25

**Comment by vzaliva** [comment]
Changing `(apply #'proof-goto-point args)` to `(apply #'proof-goto-point nil)` locally helped (thanks to @chobbes for help with debugging this)

**Comment by Chobbes** [comment]
For posterity, looks like they updated proof-general to support skipping opaque proofs when processing (`proof-goto-point` now supports an optional prefix argument to disable this feature), and it looks like the company-coq version was updated here: https://github.com/cpitclaudel/company-coq/pull/247

Relevant proof-general PR: https://github.com/ProofGeneral/PG/pull/559/

So, this should be fixed once PG is updated on MELPA.

**Comment by cpitclaudel** [comment]
Thanks folks, I reverted the broken change for now.

**Comment by erikmd** [comment]
Indeed − https://github.com/ProofGeneral/PG/pull/559 is now merged, so @cpitclaudel will be able to revert the revert anytime soon.

Just a small note BTW: to upgrade all MELPA packages easily (incl. PG & company-coq), there's now a dedicated shortcut in PG:
https://proofgeneral.github.io/#keeping-proof-general-up-to-date

**Comment by erikmd** [comment]
Hi @cpitclaudel, just a friendly reminder for #247,
so we can have a fully working `Proof-General -> Quick Options -> Processing -> Omit Proofs` feature :)

According to https://stackoverflow.com/questions/1078146/re-doing-a-reverted-merge-in-git, it should suffice to revert the revert commit in `master` (but if you prefer one could also open a new PR)

**Comment by erikmd** [comment]
BTW when you'll do this, you might want to pin this issue to make it more visible, in case some users only use MELPA for company-coq, but rely on an older/git-cloned PG? (admittedly an unfortunate situation, albeit not fully unlikeky)
Cheers, E.

**Comment by erikmd** [comment]
Hi @cpitclaudel, friendly ping :)

> it should suffice to revert the revert-commit in `master` (but if you prefer one could also open a new PR)

**Comment by cpitclaudel** [comment]
Do we have a new PG version available that I can put a dependency on while making the change?  This way the package manager will signal an issue if PG is too old.

**Comment by erikmd** [comment]
Anyway, I guess that @vzaliva or you might want to close this issue now

**Comment by vzaliva** [comment]
closing. assuming it is fixed long ago. thanks.
