### ISSUE TITLE
Title in comment are not compatible with coqdoc

### ISSUE THREAD

**Issue by Matafou** [cpitclaudel/company-coq#25]
Currently the comments detected by company-coq as "section titles" and displayed with wider fonts are not the one coqdoc considers as such. In particular, `(*** foo *)` is not considered a title, but `(** * foo *)` is. subtitle are.

It would be nice that company-coq stick to this syntax.

> Excerpt of coqdoc documentation (https://coq.inria.fr/distrib/current/refman/Reference-Manual017.html#sec579):
> 
> Sections.
> 
> Sections are introduced by 1 to 4 leading stars (i.e. at the beginning of the line) followed by a space. One star is a section, two stars a sub-section, etc. The section title is given on the remaining of the line. Example:
> 
>    (** * Well-founded relations
> 
>        In this section, we introduce...  *)
>

**Comment by cpitclaudel** [comment]
Good point! I don't use Coqdoc too much, so I hadn't looked into this. I'll look into fixing it.

**Comment by cpitclaudel** [comment]
How do I split a title across multiple lines with Coqdoc though? As in

```
(** * This is a long title,
       it continues on the next line *)
```

**Comment by Matafou** [comment]
You can't I think.

**Comment by cpitclaudel** [comment]
Got it, thanks. I wonder what's the best way to teach font-lock about this then. Probably not in font-lock-syntactic-face-function, right?

**Comment by cpitclaudel** [comment]
Note to self: this would probably work best by using a plain font-lock keyword, instead of doing it from the syntactic face function.

**Comment by cpitclaudel** [comment]
Done!

![Coqdoc](https://github.com/cpitclaudel/company-coq/raw/master/img/titles.png)

**Comment by cpitclaudel** [comment]
I found the large font a bit aggressive, so I used an inverted background.
