### ISSUE TITLE
Feature wish

### ISSUE THREAD

**Issue by Matafou** [cpitclaudel/company-coq#27]
In proofgeneral we now have a somehow-working auto insertion of the "as" close for induction and destruct (provided they are on a single tactic), and inversion (provided you are lucky :)).

Try it with latest pg by hitting C-c C-a [ when the next command is a destruct/induction without "as" close.

the feature wish is:

It would be nice to auto-insert the as close when one types as!<tab>, as for intros!<tab>.

Best,
P.

**Comment by cpitclaudel** [comment]
Implemented as `as!` :)
