### ISSUE TITLE
How do I disable the scrolling in buffer, when typing something to complete?

### ISSUE THREAD

**Issue by lczch** [cpitclaudel/company-coq#32]
Sorry, I read your responds late in Issue #8 .
When using *auto-complete-context* and *auto-complete-search-results*,
the scrolling in buffer `*goals*` or `*response*` is somewhat annoying.
I already read some code in *company-coq.el*, and guess the problem may
in the function `company-coq-search-then-scroll-up`.
Your code is beautiful ~

I read the detail in Issue #8 , and reinstalled company-coq and PG, but problem 
not disappeared. 

Detailed situation:
  For example, when I open an empty ".v" file, and type `SearchAbout "_"`,
then there's a list lemmas in `*response*` buffer.
I find the lemma `True_rect` in line 81 is what I need.
Then, naturally, I keep typing "apply True_rect" while staring at `*response*`.
To my annoy, as I'm just typing "apply True" and the company menu is appearing,
`*response*` buffer automatically scrolls to the beginning of the buffer, and I lose
my focus. ( In my window, I need to use several PageDown jumping to line 81 from line 1)

Version information:
Emacs: 24.3
company-coq: 20150718 from melpa
PG: latest from github

Thank for your help~

**Comment by cpitclaudel** [comment]
Ah, thanks, I understand now. The trick is that in #8 I saved the position of the goals buffer, but not the response buffer. Let me have a look.

**Comment by cpitclaudel** [comment]
Should be fixed on the `massive-cleanup` branch. Do you feel comfortable trying that branch out? Your help with testing this (and the refactoring that I've been working on) would be very welcome!

**Comment by lczch** [comment]
Yes, I'm very glad to ~

2015-12-22 23:40 GMT+08:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by lczch** [comment]
But I'm curious that may this intelligent scrolling in buffer become a
feature that can be turned on/off?


2015-12-23 8:54 GMT+08:00 Zhaohui Li <lizhaohui1991@gmail.com>:

**Comment by cpitclaudel** [comment]
Do you see any case where preventing the buffer from randomly scrolling wouldn't be the desired behaviour? If so, we can make it an option.

**Comment by lczch** [comment]
I have test the feature.
This time, the point will always return to what I am focusing in
*responds*,
but the window keep flashing while I am typing.
The flash seems caused  by point continue moving between (point-min) and my
focus point.
Is this fit what the fix should be?

2015-12-23 15:23 GMT+08:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by cpitclaudel** [comment]
Yes, unfortunately. There's no better way to prevent the flickering from company-coq (I'll add a patch to Proof General soon, and then things should be better).

**Comment by lczch** [comment]
It's sounds very cool to fix Proof General directly ~
Good hacking ~

**Comment by cpitclaudel** [comment]
This should be fixed in the https://github.com/ProofGeneral/PG/tree/fix-scrolling-buffers branch of PG. Maybe you could try it?

**Comment by lczch** [comment]
Sorry for delay respons...
I tried your fixed branch of PG, it's wonderful~

2016-01-01 0:55 GMT+08:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by cpitclaudel** [comment]
Great! I merged the branch, too, so the fix should be available to everyone :)

**Comment by cpitclaudel** [comment]
Thanks for your help!
