### ISSUE TITLE
Can't build company-coq: init.el is missing

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#33]
I tried building company-coq, and got this:

jil@jess:~/git/company-coq$ make elc
emacs -L . --batch --eval '(setq byte-compile-error-on-warn t)' \
	 --script ~/.emacs.d/init.el -f batch-byte-compile *.el
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50ocaml-mode.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
Loading /etc/emacs/site-start.d/51tuareg-mode.el (source)...
Cannot open load file: no such file or directory, /home/jil/.emacs.d/init.el
Makefile:16: recipe for target 'elc' failed
make: *** [elc] Error 255

I don't have an init.el file in my .emacs.d.  If you need some particular init script, maybe you should include it with the company-coq sources?

**Comment by cpitclaudel** [comment]
Should be fixed on `massive-cleanup`. In the case of `company-coq`, that Makefile is not very useful: calling byte-compile-file from Emacs does the job (and package.el takes care of compilation when installing from MELPA).

Note that the package should be fully usable without byte-compiling, though :)

**Comment by jonleivent** [comment]
I checked out the massice-cleanup branch, and tried compiling, and got this:

jil@jess:~/git/company-coq$ make elc
emacs -q -L . --batch --eval '(setq byte-compile-error-on-warn t)' \
	 --eval "(package-initialize)" -f batch-byte-compile *.el
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50ocaml-mode.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
Loading /etc/emacs/site-start.d/51tuareg-mode.el (source)...
Wrote /home/jil/git/company-coq/company-coq-abbrev.elc

In toplevel form:
company-coq-tg.el:35:12:Error: reference to free variable `for'

In toplevel form:
company-coq.el:3646:1:Error: the following functions are not known to be defined: outline-show-all, outline-show-subtree
Makefile:16: recipe for target 'elc' failed
make: *** [elc] Error 1

I guess I will try it without byte compiling - but the directions at the end of the readme don't say how to do that.  Considering that I have the MELPA version installed as well, what do I need to do in my .emacs to make sure I get the git version instead of the MELPA version?

**Comment by jonleivent** [comment]
I moved company-coq's folder out of the .emacs.d/elpa folder, and put this into my .emacs:

(add-to-list 'load-path "/home/jil/git/company-coq")
(load-file "/home/jil/git/company-coq/company-coq.el")

and it seems to work.  I'm trying out the massive-cleanup now...
