### ISSUE TITLE
when cursor is on bullet, some key bindings are missing

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#36]
This is of course using the new bullet-based subproof folder in massive-cleanup.  When stepping through a proof, my cursor landed on the next bullet, and I tried to do C-c C-u to undo a proof step, and emacs complained that there was no binding for that key.  So, apparently, the keymap being used when the cursor is on a bullet has to inherit from the normal keymap for the proof buffer.

**Comment by cpitclaudel** [comment]
Thanks. I think I saw it at some point, but couldn't reproduce it next. Normally it should inherit properly, but there may be a problem with the order in which things are loaded. I'll check.

**Comment by cpitclaudel** [comment]
Should be fixed; thanks!
