### ISSUE TITLE
Is there a way to turn off auto-completion in comments?

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#38]
Many words I use in comments are tactic names (change, replace, introduce, apply), so the auto-completion drop-down lists keep popping up on me while writing comments, which is somewhat annoying.  Is there a way to disable all auto-completion only in comments?  I may still do completion in comments, but I would rather rely on dabbrev (M-/), since it stays out of sight until used.

**Comment by cpitclaudel** [comment]
Sure, should be pretty easy. I'll look at it.

**Comment by cpitclaudel** [comment]
Done, though only in the `experimental' branch for now. Use

```
(setq company-coq-completion-predicate 'company-coq-not-in-comment-p)
```

**Comment by jonleivent** [comment]
Thanks!  That works for completion of tactics, but there is still some kind of drop-down list completion going on in comments.  Is it connected somehow to dabbrev?  Because it looks like these completions are all based on previously typed words in the buffer, like dabbrev M-/ would do.  This kind of drop-down-list-based completion is much less intrusive in comments than the tactic one - hasn't got in my way yet.

By the way, I like the rooster icon in the mode line - it's more recognizable than the hatchling (which I thought was an Easter egg until I zoomed in).  Here's an idea for a company-coq icon: a rooster in a business suit carrying a briefcase (with some math symbol on the briefcase - forall would be apropo).  Hey, PG has a spiffy icon, why can't you?

**Comment by jonleivent** [comment]
some googling of images:

http://www.gettyimages.ca/detail/photo/rooster-in-business-attire-royalty-free-image/78322845

http://www.gettyimages.com/detail/illustration/chicken-in-a-business-suit-stock-graphic/93032449

**Comment by cpitclaudel** [comment]
> Thanks! That works for completion of tactics, but there is still some kind of drop-down list completion going on in comments. Is it connected somehow to dabbrev? Because it looks like these completions are all based on previously typed words in the buffer, like dabbrev M-/ would do. This kind of drop-down-list-based completion is much less intrusive in comments than the tactic one - hasn't got in my way yet.

Indeed, I just disabled the default company-coq backend; the rest is company itself, and in particular company-dabbrev. You can adjust this by customizing `company-backends`. I'll close this issue :)

> By the way, I like the rooster icon in the mode line - it's more recognizable than the hatchling (which I thought was an Easter egg until I zoomed in). Here's an idea for a company-coq icon: a rooster in a business suit carrying a briefcase (with some math symbol on the briefcase - forall would be apropo). Hey, PG has a spiffy icon, why can't you?

That would be cool indeed! I'll think about it :)

**Comment by cpitclaudel** [comment]
>  (which I thought was an Easter egg until I zoomed in)

Well, I don't have a spiffy icon yet, but company-coq does has an easter egg now, though not the same kind thereof. Try running

```coq
Goal True.
  Timeout 15 repeat pose I.
```

with the latest MELPA build, and look at the icon :) I'm open to suggestions to make this less intrusive/more useful.

**Comment by jonleivent** [comment]
I don't see it on the master branch of git.  Is there an easy way to switch between using a git clone and MELPA?  The last time I switched from MELPA to git to test your experimental branch I deleted company-coq from the ~/.emacs.d/elpa folder.  I can obviously get it back, but what should I put in my .emacs so that I can flip between the two as needed?  Will it load the one in elpa unless I load-file the git one first?

**Comment by cpitclaudel** [comment]
Always using the git version is quite fine :) MELPA builds from that. You use a graphical Emacs, right?

**Comment by jonleivent** [comment]
Yes.  I can see the grown-up rooster icon in the mode line, in full color.  But, nothing happens with the above input, other than the eventual timeout.  Based on your changes, I expected the icon to spin, right?  Perhaps there is some other company-coq option I need to turn on to see it happen?  Or some other mode that updates the mode line more frequently?  Or maybe that's an Emacs 25 thing?

**Comment by jonleivent** [comment]
Now I see it spinning after the latest git pull.  Cute.  But - and I always think this when a moving giff pops up in my browser - why are you wasting my precious computrons?  I have a version of my project that uses Coq's par: selector to do parallel proof search, and you're going to have this thing run around like a chicken with its head cut off while Coq is stressing through those proofs on all of my cores?  Emacs takes about 9% of one core to twirl that dead chicken over my head!   ;-)

... I do like the new notification popups!

**Comment by cpitclaudel** [comment]
Ah, but the chicken is not dead :) I'm not sure I'll keep that feature in. 
In the meantime `(setq company-coq-disabled-features '(spinner))` should do the trick :)

**Comment by cpitclaudel** [comment]
I'm glad the popups are useful!

**Comment by jonleivent** [comment]
I noticed that the options checklist for company-coq-disabled-features does not include spinner - if I just set this variable as you said (and before company-coq-mode), will it possibly clash in the future with the use of Emacs options customizing?  Maybe I should use add-to-list?

**Comment by cpitclaudel** [comment]
I just gave it the wrong docstring; I fixed that now, so it should be in the list. Using the customize interface should work quite well, so feel free to do that instead of the explicit setq that I mentioned above.

**Comment by cpitclaudel** [comment]
I've changed the default to disable completion in comments, but not in escaped code sections if code blocks; that is, things will still autocomplete in `[...]` blocks in comments.

**Comment by jonleivent** [comment]
Have you tried this recently?:
```lisp
(setq company-coq-completion-predicate 'company-coq-not-in-comment-p)
```
When I set this, and then try typing anywhere in the .v file buffer, it behaves erratically.

**Comment by cpitclaudel** [comment]
Seems to work here — can you say more?

**Comment by jonleivent** [comment]
When I set that variable that way, typing in the .v buffer causes extra line breaks to be inserted after single character keystrokes, at least sometimes.   Those times seem to be when typing at the end of a line.  Suppose I have 2 lines with text separated by blank lines, like so:
```
line1


line2
```
and I start typing the word "hello" at the end of line1, I get:
```
line1h
e
l
loline2
```

Typing at the end of a buffer gives the error:
```Company: backend company-coq-master-backend error "Args out of range: #<buffer filename.v>, 1, 42880" with args (prefix)```
where filename.v is the name of the buffer.
