### ISSUE TITLE
Warning: There is no option Search Output Name Only.

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#39]
Clement,

Is this warning that appears repeatedly in my response buffer due to my using the experimental branch without the necessary patches?

**Comment by cpitclaudel** [comment]
No, you probably found a bug with my recent refactoring :/ Thanks for reporting it! Normaly company-coq does capability detection upon launch to check what patches are available.

Is this 8.5?

**Comment by jonleivent** [comment]
Yes, it is 8.5, git version 37cc370

**Comment by cpitclaudel** [comment]
That's surprising :/ Can you try running `Set Search Output Name Only.`? This option has been in 8.5 for a while now.

**Comment by jonleivent** [comment]
jil@jess:~/git/coq$ coqtop
Welcome to Coq jess:/home/jil/git/coq,v8.5 (37cc37090fcbabb9546a79558c9420e532701be4)

Coq < Set Search Output Name Only.
Warning: There is no option Search Output Name Only.

**Comment by cpitclaudel** [comment]
Ah, interesting. Looks like my patch was merged in trunk, not in 8.5. My detection logic is still broken, though. I'll fix the latter and I'll investigate the former.

**Comment by cpitclaudel** [comment]
Should be fixed. Thanks for reporting!
