### ISSUE TITLE
Completion of constants from other files does not work even if Coq is patched with SearchMinimal.patch

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#41]
In 8.4pl6+ltacprof+SearchMinimal, the command `Set Search Minimal.` succeeds with no warning (`Set Search Minimal2.` succeeds with the warning `Warning: There is no option Search Minimal2.`), but the log in `*coq*` begins
```
Welcome to Coq 8.4pl6 (January 2016)
�Warning: /home/jgross/Documents/repos/fiat/src/Common/Tactics was previously
 bound to Fiat.Common.Tactics; it is remapped to <>�

<prompt>Coq < 1 || 0 < </prompt>Redirect "/tmp/coq5789WNY" Test Search Output Name Only.
Error: Unknown command of the non proof-editing mode.

<prompt>Coq < 1 || 0 < </prompt>Print Grammar tactic.
```

**Comment by cpitclaudel** [comment]
Ah, did I forget to update the path? :/

**Comment by cpitclaudel** [comment]
I'll have a look immediately; sorry about this.

**Comment by cpitclaudel** [comment]
Indeed, the relevant fork is here: https://github.com/cpitclaudel/coq/commits/V8.4pl2-company-coq

**Comment by cpitclaudel** [comment]
I've updated the README on the `experimental` branch of company-coq, but not on master.

**Comment by JasonGross** [comment]
Would it be possible to get a patch in the repo that applies to 8.4pl1-8.4pl6 (and another for 8.5/trunk), that applies all of the relevant changes, rather than needing to get them from a fork?

**Comment by cpitclaudel** [comment]
Sure, I'll create it.

**Comment by cpitclaudel** [comment]
Here: https://github.com/cpitclaudel/company-coq/blob/experimental/etc/8.4-additions.patch :)

**Comment by cpitclaudel** [comment]
I also added one for trunk.
