### ISSUE TITLE
TAB should indent in more places

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#42]
Here is a location that `TAB` should indent (the `end`), but it does not.

![image](https://cloud.githubusercontent.com/assets/396076/12184808/891b80d8-b565-11e5-9168-987412c4b821.png)

**Comment by cpitclaudel** [comment]
Thanks. Can you try adding `(define-key company-active-map [remap company-complete-common] #'company-indent-or-complete-common)` to your `.emacs` and tell me what you think?

Normally this is a user customization, but it might make sense to add it to company-coq's `company-defaults` feature.

**Comment by cpitclaudel** [comment]
Also, it looks like you got symbols completion working! That's exciting :)

**Comment by cpitclaudel** [comment]
And I pushed a large company-coq update yesterday night, so I'll welcome your feedback on that  :)

**Comment by JasonGross** [comment]
Updated company-coq just now, added
```
(define-key company-active-map [remap company-complete-common] #'company-indent-or-complete-common)
```
to right below `(company-coq-initialize)`.  It seems to no longer try to complete `end`?  But I still get that `TAB` does not indent when the dropdown is active, e.g.,
![image](https://cloud.githubusercontent.com/assets/396076/12207005/38152f56-b612-11e5-8c3e-0db98e7fb0b0.png)
