### ISSUE TITLE
Error building MELPA version 20160112.146 in Emacs 24.4.1

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#45]
[melpa-company-coq-build-bug.txt](https://github.com/cpitclaudel/company-coq/files/87770/melpa-company-coq-build-bug.txt)

**Comment by cpitclaudel** [comment]
Oh, thanks for pointing this out. Wonder what might cause this. I'll look into it.
These are warnings though, right? Not errors?

**Comment by jonleivent** [comment]
The last is an error.

**Comment by cpitclaudel** [comment]
Aaargh yes.

**Comment by cpitclaudel** [comment]
Just pushed a fix

**Comment by cpitclaudel** [comment]
Emacs 25 syntax strikes again

**Comment by cpitclaudel** [comment]
I should just stop developing in 25

**Comment by cpitclaudel** [comment]
Alright, I can reproduce the warnings too.

**Comment by cpitclaudel** [comment]
Both should be fixed now. Thanks a lot!
