### ISSUE TITLE
No completion for `nat_rect`

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#46]
Not for `bool_rect` nor `Datatypes.nat_rect` either.  For that matter, there's no completion for `Coq.Init.Datatypes.*`, nor `Init.Datatypes.*` nor `Datatypes.nat`

![image](https://cloud.githubusercontent.com/assets/396076/12281284/cee47aba-b962-11e5-8944-f28207763668.png)

![image](https://cloud.githubusercontent.com/assets/396076/12281303/fece4198-b962-11e5-9897-39a9c9d31fef.png)

**Comment by cpitclaudel** [comment]
Indeed; this is due to https://github.com/cpitclaudel/company-coq/blob/master/company-coq.el#L396; introduced almost a year ago in https://github.com/cpitclaudel/company-coq/commit/69a9c123afb01daaa02929ea00761e4a5b310f9e. I guess at that time I wasn't too convinced that these lemmas were very useful, and I was having plenty of performance issues, so these were obvious candidates for filtering out. Do we put them back in?

**Comment by JasonGross** [comment]
If they don't degrade performance too much, I'd vote for yes.  I use them a lot because Coq 8.4 doesn't like evars generated by underscores inside of `match` statements.  (Where by "doesn't like", I mean, "has a lot of trouble solving any unification problem involving".)

Is this also responsible for the lack of `Coq.Init.Datatypes.*` completions?

**Comment by cpitclaudel** [comment]
I don't think so; I think the Coq.Init.Datatypes.* part is that these things are available a different name; aren't they? Generally, company-coq will only auto-complete based on the shortest name available for any identifier, because that's the only thing Coq will give it :/

**Comment by JasonGross** [comment]
It's really inefficient, but you can `Locate` each constant to get the longest name for that constant. :P Should we ask for a `Set Printing Fully Qualified Names` option or something?

**Comment by cpitclaudel** [comment]
Potentially; but then I'd have two load twice as many names: the qualified ones and the unqualified ones, which the user will want to use too. We should push for a completion API instead: If coq had an API that I could query to get "the top 10 identifiers starting with ..." then "then next ten identifiers stating with ..." etc. It would support all of this easily, and the performance issues would vanish as well.

**Comment by cpitclaudel** [comment]
Here is a trivial example of such an API: https://www.gnu.org/software/octave/doc/interpreter/Commands-For-Completion.html

**Comment by cpitclaudel** [comment]
I'm open to trying the nat_rect thing out: to use it you still need to run trunk or a patched version of coq and set `company-coq-live-on-the-edge`, so I won't affect too many people.
