### ISSUE TITLE
� is not a rooster

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#48]
Not sure if there's any (good?) way to fix this, but I figured it might be useful to note that the rooster doesn't show up in my remote emacs (maybe because I had to compile without support for tiffs and gifs?):
![image](https://cloud.githubusercontent.com/assets/396076/12305508/2e419376-ba03-11e5-8d55-1279c05461c0.png)

**Comment by cpitclaudel** [comment]
It's a font issue on your local machine (terminals don't support PNGs). Try installing [Symbola](http://users.teilar.gr/%7Eg1951d/Symbola.zip)? ?

**Comment by cpitclaudel** [comment]
Although Windows 10 should come with Segoe UI Emoji, so I'm not too sure.

**Comment by JasonGross** [comment]
MinTTY has a very limited list of (fixed-width only?) fonts:
![image](https://cloud.githubusercontent.com/assets/396076/12305958/54ca27ae-ba05-11e5-9fc1-9f086ef15dfc.png)

**Comment by cpitclaudel** [comment]
Fair enough. Good symbol support on TTYs is hard, so I've pushed a change that drops that icon unless prettification is enabled (it's disabled by default in TTYs).
