### ISSUE TITLE
company-coq.el:64:1:Error: Cannot open load file: no such file or directory, company

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#50]
I just installed cask and tried building company-coq (I was previously running from sources), and got this:

il@jess:~/git/company-coq$ make
env --unset INSIDE_EMACS EMACS=emacs cask clean-elc
env --unset INSIDE_EMACS EMACS=emacs cask build
Compiling /home/jil/git/company-coq/company-coq-abbrev.el...
Wrote /home/jil/git/company-coq/company-coq-abbrev.elc
Compiling /home/jil/git/company-coq/company-coq-pkg.el...
Wrote /home/jil/git/company-coq/company-coq-pkg.elc
Compiling /home/jil/git/company-coq/company-coq-tg.el...
Wrote /home/jil/git/company-coq/company-coq-tg.elc
Compiling /home/jil/git/company-coq/company-coq-utils.el...
Wrote /home/jil/git/company-coq/company-coq-utils.elc
Compiling /home/jil/git/company-coq/company-coq.el...

In toplevel form:
company-coq.el:64:1:Error: Cannot open load file: no such file or directory, company
env --unset INSIDE_EMACS EMACS=emacs cask package
Wrote /home/jil/git/company-coq/dist/company-coq-readme.txt

Note that I have company in my .emacs.d/elpa folder, so what is going wrong?

**Comment by cpitclaudel** [comment]
Did you run `cask install` first?

**Comment by cpitclaudel** [comment]
Cask is designed to work independently of you .emacs; it installs a local copy (other languages call that a virtualenv) or each required package.

**Comment by jonleivent** [comment]
Oh - that helps.  Should the company-coq Makefile run cask install itself?

**Comment by cpitclaudel** [comment]
Sure thing :)
