### ISSUE TITLE
enter should not merely end completion of completly typed-in keyword

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#51]
The following case keeps biting me:

  match foo with
  pattern => idtac

When I hit enter after fully typing idtac, all that happens is that completion is aborted.  Which forces me to type a second enter to start the next line.  However, my fingers won't cooperate, and start typing the next line after hitting the first enter, so I end up with:

  match foo with
  pattern => idtacend

or "idtac|another pattern" or something like that.  Same for other optional extra arg cases, like with fail, constructor, etc.

Would it be possible to have enter both stop the attempt at further completion AND do a newline-and-indent in the case where the user completely typed a complete valid keyword themselves?  Is there already such an option?

**Comment by cpitclaudel** [comment]
Sure, I can do that. It already happens in many cases, but not all; I'll look at generalizing it (it works with `match` or `with`, for example).

**Comment by cpitclaudel** [comment]
Done, please test! :)

**Comment by jonleivent** [comment]
It works in the few cases I tested!  Thanks!

**Comment by cpitclaudel** [comment]
Yay! Thanks for the suggestion.
