### ISSUE TITLE
company-coq doesn't like some versions of Coq on Windows

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#52]
`company-coq-tg--parse-toplevel: Toplevel parsing failure [(Anomaly: Uncaught exception Invalid_argument (Sys.signal: unavailable signal))]`

Are you using `Timeout`?

**Comment by JasonGross** [comment]
Urg, this happens on almost every character, and the error messages make typing a bit laggy.

**Comment by cpitclaudel** [comment]
Yes, I use it as a safety measure in case some command that I send go wrong. I guess we'll have to live dangerously on Windows :)

**Comment by JasonGross** [comment]
Rather than doing this, can you instead check at the beginning whether `Timeout` works?  Whether or not `Timeout` works on Windows depends on what compilation stack you use to compile it...  (I think the one you download from the website, or build with the sdk, works fine, but the one built with the cygwin ocaml package doesn't, or vice versa...)

**Comment by cpitclaudel** [comment]
Not really; company-coq already has three capability detection routines, and I don't think this warrant an extra one; this Timeout thing was only a safety measure to begin with.

Plus, it's not obvious to me that Timeout should return an error instead of a warning on Windows.
