### ISSUE TITLE
overlylong types causes the feedback buffer to gain an extra line, causing an annoying flickering effect as I type (and possibly lagging emacs)

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#53]
![image](https://cloud.githubusercontent.com/assets/396076/12380890/63de1cf2-bd4b-11e5-8111-3c6e403ab8a5.png)
![image](https://cloud.githubusercontent.com/assets/396076/12380892/6a18b870-bd4b-11e5-837b-7a451f9d4509.png)

The description buffer (or whatever it's called) should never gain an extra line.

**Comment by cpitclaudel** [comment]
This should already have been taken care of, but I guess it wasn't enough. Should be fixed now :)
