### ISSUE TITLE
Something very wrong in f1038c9 with goal window underline

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#54]
What's going on in the goals window with the underline?  Do I have to get a better font or something?

![screenshot-emacs24 jess home-1](https://cloud.githubusercontent.com/assets/7363878/12381638/237cf65e-bd5c-11e5-8804-a7f9d3550064.png)

**Comment by jonleivent** [comment]
I found the option Company Coq Goal Line Character, and set it to '='.  I tried some graphical characters that my font manager claims Inconsolata can display, but they all have the empty squares look when used here.  I know I have an adequate math font, as the other company-coq folded symbols all work just fine.

**Comment by cpitclaudel** [comment]
Ah, indeed, that doesn't look the best. Looks like your font doesn't have ═? And yet you had no issues with the previous goal line prettification, did you?

**Comment by cpitclaudel** [comment]
Let's try something different. I've pushed a potential fix; can you have a look? Thanks!

**Comment by jonleivent** [comment]
The fix you just pushed works - I now get a nice unbroken line.  Thanks again, Clement!  However, perhaps you misunderstood my second message - it was after the bad goal line with empty boxes appeared that I set Company Coq Goal Line Character to '=', and that worked, since my font does have '=', just not the default character used for the goal line originally.  I do find it strange that I was getting empty boxes despite the fixes I did per your suggestion to Inconsolata font.  Perhaps the mysteries behind Emacs and font choices for special characters are unknowable!

**Comment by cpitclaudel** [comment]
Glad it worked :) The whole point of the original commit was to get a pretty unbroken goal line though, so reverting to `=` would have been a disappointing workaround (in most fonts that I checked sequences of `=` don't look continuous)
