### ISSUE TITLE
Missing completions for `Module Export`, `Module Import`

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#55]
![image](https://cloud.githubusercontent.com/assets/396076/12383291/4bf6f11e-bd72-11e5-928f-4c91b178a969.png)

**Comment by cpitclaudel** [comment]
Done. Though I wonder if it would be better to just expand that into two options (the manual has it as `Module [Import|Export]`, so company-coq displays it as one entry with two choices.
