### ISSUE TITLE
No patch for [Search Output Name Only] for 8.5

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#56]
The [trunk-additions patch](https://raw.githubusercontent.com/cpitclaudel/company-coq/experimental/etc/trunk-additions.patch) does not seem to give you `Search Output Name Only`, which doesn't seem to be in Coq v8.5.

**Comment by cpitclaudel** [comment]
Indeed, sorry about that. I'll fix it soon.

**Comment by cpitclaudel** [comment]
Wait, isn't that expected, actually? That patch is for trunk.

**Comment by JasonGross** [comment]
I can't seem to find a corresponding patch for 8.5.  I presume there should be one, no?
