### ISSUE TITLE
enhancement: one-line bullets/braces maybe shouldn't get folding treatment

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#57]
I noticed some implicit args I had at the beginning of a line were being treated as proof braces with respect to folding because, well, they are wrapped in braces, too.  They get highlighted as if they were proof braces, with a tool tip about folding.  I know it is hard to determine which is which due to the difficulties of the syntax - but maybe an easy trick is to just check if they are limited to a single line, and in that case don't give them the folding treatment.  After all, the folding treatment is useless for one-line proof bullets/braces anyway.

**Comment by cpitclaudel** [comment]
Ah, that's a great idea. It should work nicely for braces.
