### ISSUE TITLE
Unwanted "Company-Coq--Keybindings" mode.

### ISSUE THREAD

**Issue by alxest** [cpitclaudel/company-coq#6]
I followed the config, 
~~~
(require 'company-coq)
(add-hook 'coq-mode-hook #'company-coq-initialize).
~~~
However, "Company-Coq--Keybindings" mode is always on.
Especially, in term-mode, hitting space calls "company-coq-maybe-exit-snippet", preventing insertion of space.

**Comment by cpitclaudel** [comment]
Thanks for the report. That's strange. Is the keybinding minor mode active in other buffers than Coq buffers? Which term-mode buffer are you seeing this in?

**Comment by alxest** [comment]
Yes, I saw keybinding minor mode active in other buffers too.
I use multi-term package. (with term)

**Comment by cpitclaudel** [comment]
Thanks for the reply. Do you have an error message when you insert a space in term buffers? Normally the keybindings mode should only be activated in coq buffers.
________________________________

**Comment by alxest** [comment]
Um, I don't see any error message. I have seen through *Messages* buffer but it looks normal.
You may want to see my .emacs.d (https://github.com/alxest/.emacs.d)
company-coq configs are in ".emacs.d/init.el"'s bottom.

**Comment by cpitclaudel** [comment]
I just pushed a fix; it should hit MELPA in a few hours. Thanks for spotting this!
