### ISSUE TITLE
Completion list disables coloring of processed lines

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#60]
![image](https://cloud.githubusercontent.com/assets/396076/12460988/8efdd9d2-bf84-11e5-983e-38d441f29e56.png)

I think the lines above the current one should remain blue.  (This is minor.)

**Comment by cpitclaudel** [comment]
This is a known company issue, due to the way overlays work, I think. There are many similar ones, such as https://github.com/company-mode/company-mode/issues/299, as well as 369, 376, 396, and others :)
