### ISSUE TITLE
Disappearing options in the customization window

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#61]
I have noticed this several times, most recently with company-coq-features/code-folding-elipses.  In the Emacs Customization window - say when customizing options matching "company-coq-features", one gets this:

![screenshot-emacs24 jess home-2](https://cloud.githubusercontent.com/assets/7363878/12517761/88300f7e-c102-11e5-83f8-9a23e875dc95.png)

but when trying to expand the code-folding-elipses option via clicking the left-side triangle bullet, one gets:

![screenshot-emacs24 jess home-3](https://cloud.githubusercontent.com/assets/7363878/12517779/a0ce2ab6-c102-11e5-83db-c48326369871.png)

The option disappears!  I wish I recalled what other cases I saw this happen with...

**Comment by cpitclaudel** [comment]
Indeed! Woops. The variable had an incorrect type declaration.
