### ISSUE TITLE
No completion for `Set Universe Polymorphism`

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#62]
![image](https://cloud.githubusercontent.com/assets/396076/12530946/8ccf0fca-c1bc-11e5-9537-a7fd032a6c61.png)

**Comment by cpitclaudel** [comment]
Yup, I had the same idea :) Fixed it locally, will push tonight.
Worse though: `Monomorphic Constraint` doesn't seem documented.

**Comment by JasonGross** [comment]
Thanks!  Reported as [bug 4515](https://coq.inria.fr/bugs/show_bug.cgi?id=4515)
