### ISSUE TITLE
company-coq kills Coq 8.5 when -debug is passed

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#63]
Say I have a file like
```coq
(* -*- coq-prog-args: ("-emacs" "-debug") -*- *)
Goal True.
```
For whatever reason, [`Print Grammar tactic.` gives some strange `sh: 1: dot: not found` messages when `dot` is not installed](https://coq.inria.fr/bugs/show_bug.cgi?id=4526), and I think company-coq barfs on these messages.

**Comment by cpitclaudel** [comment]
Should we call this a Coq issue? I'm a bit wary of adding code to `company-coq` to work around this, but I can do it if needed. If anything, I could fail more gracefully.

**Comment by JasonGross** [comment]
[Enrico said: "This is the -debug flag that tries to call dot to print the STM state."](https://coq.inria.fr/bugs/show_bug.cgi?id=4526#c1) and resolved the bug as invalid.  So I'd say you should handle it, unless you think Coq should behave differently and want to reopen the bug report?.

**Comment by JasonGross** [comment]
(Use case: I want to get backtraces on anomalies in PG, without having to disable company-coq manually.)

**Comment by jonleivent** [comment]
Jason - why don't you just install graphviz/dot?  Once I do that, the bug disappears.

**Comment by JasonGross** [comment]
Sure.  I think it would be nice to get either an error message that says "please install graphviz or disable company-coq" or, better, "Disabling company-coq; -debug is not supported unless graphviz/dot is installed", and then leave PG running while disabling company-coq for that run.  But if that's too much trouble, or not worth it, that's fine.

**Comment by jonleivent** [comment]
Coq should make sure dot is installed at config time, perhaps.  Not to make excuses for the devs, but requirements on external software are very difficult to keep track of.

**Comment by cpitclaudel** [comment]
I think it's a lot of trouble for a pretty niche feature: if Coq requires dot to run in debug mode, then it should complain about that absence earlier. Or it could check for graphviz instead of trying to invoke it directly upon Print Grammar Tactic.

Would installing dot be an acceptable workaround for you? If so, I'll close this. `-debug` on my machine gives more output, too, so I'm not sure what another way to proceed would be:


```
Error: in _: Unknown or unprintable grammar entry.
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
frame @ file "format.ml", line 438, characters 6-24
frame @ file "format.ml", line 423, characters 8-33
raise @ file "format.ml", line 195, characters 41-52
```

**Comment by jonleivent** [comment]
I suspect that if the lack of check for dot was put into Coq's bugzilla with a different categorization and explanation (installation dependencies should include dot, or configure should check for it, or both), it wouldn't get closed so easily with no fix.  It's worth a shot.

**Comment by cpitclaudel** [comment]
Indeed, a new bug report suggesting to complain early if dot is not found in debug mode may be appropriate (though not high priority, IMHO). In the meantime, since installing dot should fix the problem, I'll close this. Jason, if you think there's a reason why users may want to use debug w/out installing dot, please do feel free to reopen, and I'll tighten up the grammar parsing code.
