### ISSUE TITLE
Auqamacs key binding

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#65]
I have not figured out what modified keys I can use in Auqamacs with mouse click to achieve "Control+Click" functionality.

**Comment by cpitclaudel** [comment]
Thanks for the reminder. I'm going to try to borrow a mac in the next few days to try company-coq in aquamacs.

**Comment by cpitclaudel** [comment]
I just looked at this. The issue is that Aquamacs simply refuses to recognize `Control-Click`: instead, it translates it to `right click`. The replacement happens at a much too low level, so there's nothing I can do about it.

As a workaround I added `M-F12` as an alternative keybinding for this feature. What do you think?

**Comment by vzaliva** [comment]
Sorry for the delay with answer. M-F12 is not very convenient, because it requires using FN key in default Mac keybinding. Anyway, I found a way to make control-click work under Aquamacs. I am not Elisp hacker, so here is quick and dirty solution which works. Hopefully you can rework it and include into main package. I will be glad to test:

```
(defun company-coq-toggle-aquamacs-definition-overlay (event &optional  prefix)
  "Toggle inline docs for symbol at point in Aquamacs Emacs."
  (interactive)
  (company-coq-error-unless-feature-active 'inline-docs)
  (if company-coq-definition-overlay
      (company-coq-clear-definition-overlay)
    (company-coq-show-definition-overlay-under-pointer event)
    (message (substitute-command-keys "Press \\[company-coq-toggle-definition-overlay] again to hide the inline docs."))))

(custom-set-variables
     '(osx-key-mode-mouse-3-behavior
     #'company-coq-toggle-aquamacs-definition-overlay))
```
