### ISSUE TITLE
Error on typing [End foo]

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#7]
If I type
```coq
Section fooooo.
End foo
```
when I type the last `o` on the `End foo`, I get an error:

![image](https://cloud.githubusercontent.com/assets/396076/6975594/20b21bae-d96c-11e4-96b2-6ef876c30d83.png)

**Comment by cpitclaudel** [comment]
Hmm. I can't reproduce this on my machine. Do you have the same error after running <kbd>M-x show-paren-mode</kbd>?

**Comment by JasonGross** [comment]
Yes, I still have the same error after that.

**Comment by cpitclaudel** [comment]
Ah, perhaps the code implicitly relies on newer features of Proof-General (Newer PGs use SMIE for indentation, which sets `show-paren-data-function`, which I use to find the corresponding section opening).

**Comment by cpitclaudel** [comment]
I guess the only way around this is to add a null check before calling that function. I'll do that.

**Comment by JasonGross** [comment]
Thanks!

**Comment by cpitclaudel** [comment]
This is not the most satisfactory fix though; it just disables section name completion if `show-paren-data-function` isn't available. In the long run PG probably will get better support for navigating around code blocks, and then `company-coq` can make use of that support.
