### ISSUE TITLE
Rooster no longer rotates when processing buffer

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#75]
(I also liked the old rooster image better; this one is less recognizably a rooster.)
![ezgif-2021556183](https://cloud.githubusercontent.com/assets/396076/12793086/c09947c6-ca7c-11e5-9694-70dd5fecf0c5.gif)

**Comment by cpitclaudel** [comment]
It's not a picture anymore on your screenshot; it's a unicode character. Did you update Emacs recently?

**Comment by cpitclaudel** [comment]
What does `M-: (image-type-available-p 'imagemagick) RET` return?

**Comment by JasonGross** [comment]
It gives me `t`.  The view says:
```
GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)
 of 2014-03-07 on lamiak, modified by Debian
```

**Comment by cpitclaudel** [comment]
Hmm. What does `M-: (company-coq--lighter-string)` return?

**Comment by JasonGross** [comment]
`"company-🐤"`

**Comment by JasonGross** [comment]
The rooster is fixed in any fresh instance of emacs that I open, though.  So let me know if you want to keep debugging this issue, or feel free to close it.

**Comment by cpitclaudel** [comment]
Thanks; let's reopen this if it appears again :)
