### ISSUE TITLE
Incorrect highlighting/collapsing of bullets

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#76]
I'm not sure if this is a company-coq issue or a PG issue, but this minus sign is incorrectly highlighted as a proof bullet.  (Also not sure if this is worth fixing.)
![image](https://cloud.githubusercontent.com/assets/396076/12825034/46e8fa86-cb42-11e5-97d3-e092d355c3c2.png)

**Comment by cpitclaudel** [comment]
Definitely company-coq, and I have no idea how to fix it :) It's a known limitation of the heuristic used for highlighting bullets.

**Comment by cpitclaudel** [comment]
I'm going to close this as wontfix. Until Coq provides a good way to get a parse tree of a document, I can't do better than apply heuristics to guess what to highlight, and indeed there will be incorrect cases like this one.
