### ISSUE TITLE
company-coq init error: coq-mode-map

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#77]
This is company-coq version e0359c6, emacs 24.4.1.

Here's the stack from emacs --debug-init:

Debugger entered--Lisp error: (void-variable coq-mode-map)
  (copy-keymap coq-mode-map)
  (let ((map (copy-keymap coq-mode-map))) (define-key map (kbd "<down-mouse-3>") (function company-coq-features/refactorings--show-menu)) (define-key map (kbd "<mouse-3>") (function ignore)) (define-key map (kbd "<C-down-mouse-1>") (function company-coq-features/refactorings--show-menu)) (define-key map (kbd "<C-mouse-1>") (function ignore)) (define-key map (kbd "<menu>") (function company-coq-features/refactorings--show-menu-at-point)) map)
  (defconst company-coq-features/refactorings--keymap (let ((map (copy-keymap coq-mode-map))) (define-key map (kbd "<down-mouse-3>") (function company-coq-features/refactorings--show-menu)) (define-key map (kbd "<mouse-3>") (function ignore)) (define-key map (kbd "<C-down-mouse-1>") (function company-coq-features/refactorings--show-menu)) (define-key map (kbd "<C-mouse-1>") (function ignore)) (define-key map (kbd "<menu>") (function company-coq-features/refactorings--show-menu-at-point)) map) "Keymap for refactoring tags.\nSee `company-coq-features/code-folding--keymap' for more info.")
  eval-buffer(#<buffer  *load*-974657> nil "/home/jil/git/company-coq/company-coq.el" nil t)  ; Reading at buffer position 233850
  load-with-code-conversion("/home/jil/git/company-coq/company-coq.el" "/home/jil/git/company-coq/company-coq.el" nil nil)
  load("/home/jil/git/company-coq/company-coq.el" nil nil t)
  load-file("/home/jil/git/company-coq/company-coq.el")
  eval-buffer(#<buffer  *load*> nil "/home/jil/.emacs" nil t)  ; Reading at buffer position 2290
  load-with-code-conversion("/home/jil/.emacs" "/home/jil/.emacs" t t)
  load("~/.emacs" t t)

**Comment by cpitclaudel** [comment]
Fixed (I think). Thanks a lot and sorry for the trouble :/ I need to set up automatic testing; there are just too many version of Emacs + PG.
