### ISSUE TITLE
LaTeX-style completions stop working sometimes

### ISSUE THREAD

**Issue by wilcoxjay** [cpitclaudel/company-coq#78]
When I work in buffer for a while, occasionally company-coq stops suggesting LaTeX completions like \gamma. If I close and re-open the file, it starts working again.

I'm filing this issue mostly as a request for help debugging this; I don't even know where to start.

I'm on OS X, using GNU Emacs 24.5.1 with company-coq 0533c8, and a recent (post-release but not quite HEAD) build of the 8.5 branch of Coq with Clément's patches applied. I've configured company-coq to live on the edge. I'm willing to try to reproduce this on other versions if that's helpful.

**Comment by cpitclaudel** [comment]
Hey Jay,

Thanks for reporting the bug. Your setup seems fine; there shouldn't be a need to change configs to debug this.

Are other completions still available when this happens? In any case: LaTeX style completions are provided by an auxiliary package called company-math. Company-mode (the completion engine that company-coq uses) pulls candidates from a list of backends; company-coq sets it up by adding three backends to the front of `company-backends`:

* company-math-symbols-unicode, which handles LaTeX style completions
* company-coq-choices-backend, which isn't very important for this discussion
* company-coq-master-backend, which has all of `company-coq` candidates

Thus is something breaks, it could be either company-math-unicode breaking, or company not calling company-math-symbols-unicode, or another type of bad interaction.

Next time this happens, can you try:

* Checking that company is set up properly by inspecting the value of `company-backends` (`C-h v`); it should be a list starting with `(company-math-symbols-unicode company-coq-choices-backend company-coq-master-backend ...`
* Checking that company-math is working properly by running `M-: (company-math-symbols-unicode 'candidates "right")`; it should return a list of completions
* Checking that prefix detection works fine in company-math by running (progn (insert " \\abc") (company-math-symbols-unicode 'prefix)); it should return `"abc"` (more or less)
* Checking that company calls company-math-unicode as expected; for that type ` \right` and then run `M-x company-manual-begin`. Does it show `\rightarrow` etc?

If all tests but the last succeed, then it will probably be time to crank out the debugger :)

**Comment by wilcoxjay** [comment]
I've got this reproducing fairly consistently now. It appears to be related to opening other Coq files. Steps to reproduce on my machine:
  1. Open a file and hit `C-c C-n` a few times to get everything going. It doesn't appear to matter what the exact contents of these lines are.
  2. At this point typing `\bet` should suggest completing to ß.
  3. Open a different .v file (doesn't matter which one as far as I can tell). Without actually loading this file, LaTeX completions work.
  4. Switch back to the still-loaded old file. LaTeX completions no longer work.

Other completions are still available when the bug is manifesting. The normal company-coq completions still show up. For example, if I type `\bet` expecting to get a completion for ß, I instead see completions like `between`. 

* The value of `company-backends` is:
```
(company-coq-choices-backend company-coq-master-backend company-coq-choices-backend company-coq-master-backend company-coq-choices-backend company-coq-master-backend company-math-symbols-unicode company-coq-choices-backend company-coq-master-backend company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
                             (company-dabbrev-code company-gtags company-etags company-keywords)
                             company-oddmuse company-files company-dabbrev)
```
I'm not sure why there are several copies of various things.
* `M-: (company-math-symbols-unicode 'candidates "right")` seems okay, it returns: 
```
(#("rightarrow" 0 10 (:symbol "→")) #("rightharpoonup" 0 14 (:symbol "⇀")) #("rightharpoondown" 0 16 (:symbol "⇁")) #("rightleftharpoons" 0 17 (:symbol "⇌")) #("rightsquigarrow" 0 15 (:symbol "↝")) #("rightthreetimes" 0 15 (:symbol "⋌")) #("rightharpoonaccent" 0 18 (:symbol "⃑")) #("rightwavearrow" 0 14 (:symbol "↝")) #("rightarrowtail" 0 14 (:symbol "↣")) #("rightleftarrows" 0 15 (:symbol "⇄")) #("rightrightarrows" 0 16 (:symbol "⇉")) #("rightdasharrow" 0 14 (:symbol "⇢")) ...)
```
* `(progn (insert " \abc") (company-math-symbols-unicode 'prefix))` returned nil and inserted a non-printable character in the buffer, so I tried escaping the backslash, which inserted "abc" and printed the message `#("abc" 0 3 (fontified nil))`, which seems like what you were going for.
* If I type `\right` I immediately get a list of non-LaTeX completions for "right". If I then run `M-x company-manual-begin`, I get the same thing; no `\rightarrow` or any other LaTeX thing is in the list.

**Comment by cpitclaudel** [comment]
Ah, cool, this makes a lot of sense. I'll fix it and explain a bit more soon. Thanks!

**Comment by cpitclaudel** [comment]
Should be fixed :) The issue was that enabling company-coq enables it in all Coq buffers, but the unicode-math-symbols-backend module was only being enabled in the current buffer; in all other buffers, this caused the master backend to be moved in front of the math-symbols one, and thus to take priority over it.
