### ISSUE TITLE
match! doesn't handle type parameters correctly

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#81]
This is probably due to a bug in Coq's Show Match command, but I figured I'd run this by you first:

Inductive Foo(n : nat) : Set :=
| Foo1 (i : bool) : Foo n
| Foo2 (x : nat) : Foo n.

Goal Foo 2 -> True.
Proof.
  intro f.
  refine ( (*match! used here on type Foo*)
      match f with
      | Foo1 i => _ (*Error: The constructor Foo1 (in type Foo) expects 2 arguments.*)
      | Foo2 x => _
      end).

The patterns should of course be "Foo1 _ i" and "Foo2 _ x".

**Comment by jonleivent** [comment]
Similarly, when Set Asymmetric Patterns is not set (the default), match! still puts implicits into the pattern.

**Comment by cpitclaudel** [comment]
Yup, definitely a Coq bug:

```
$ rlwrap /build/coq-8.5/bin/coqtop
Welcome to Coq 8.5 (January 2016)

Inductive Foo(n : nat) : Set :=
| Foo1 (i : bool) : Foo n
Coq < | Foo2 (x : nat) : Foo n.
Foo is defined
Foo_rect is defined
Foo_ind is defined
Foo_rec is defined

Coq < Show Match Foo.
match # with
 | Foo1 i =>
 | Foo2 x =>
 end
 ```

Can you report it on the Coq tracker?

**Comment by jonleivent** [comment]
Will do.

**Comment by jonleivent** [comment]
[https://coq.inria.fr/bugs/show_bug.cgi?id=4563](url)

By the way, wouldn't it be better if match! took a constr instead of a type, and looked up the type of the constr as well as filled it into the match discriminee?  For instance, if the user wants to do 

match (some-function args...) with ...

the current mechanism will require them to look up the type of the result - while this can easily be done by company-coq with a Check command for them.

**Comment by jonleivent** [comment]
While I'm on the subject, here's another wish:  when the names generated for pattern bindings by Show Match are the same as names that already exist in the context, maybe company-coq can prevent name clashes by appending an integer (operate like fresh, in other words).

**Comment by cpitclaudel** [comment]
By context, do you mean explicitly in the context (as in the proof context)? Or do you mean in the list of arguments of a function that's being defined?

**Comment by cpitclaudel** [comment]
Thanks for reporting the bug!

**Comment by jonleivent** [comment]
There probably isn't a way.  I was thinking to narrowly: using "refine (match! ...)", with the proof context admitted up to just before the refine.  In that case, the context is meaningful to the match.  But, obviously, not most other cases.  So, there's no useful context established in most cases to do a Check in, nor to search for name clashes.

**Comment by cpitclaudel** [comment]
Indeed, it is a bit tricky :/ One mistake I often make is that I will write something like 

```
Definition func a :=
  match!
```

and then type `a` instead of the type of `a`, somehow hoping that Coq will guess the type... but I didn't even specify it in the signature, so of course there's no way it could work :)

I'll close this bug for now, as it will fix itself (hopefully!) once it's fixed on the Coq side.
