### ISSUE TITLE
subscripts mess up cursor positioning

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#85]
Type `pose foo_bar_baz`, then move the cursor to after `bar`, then type `<BS><BS><BS>bar`.  This should be a no-op, and yet I get `foo_b_arbaz`.

**Comment by cpitclaudel** [comment]
Is this with an up-to-date company-coq? I don't think we display subscripts for underscores with letters anymore (did we ever?).

**Comment by cpitclaudel** [comment]
Oh, I see, sorry.

**Comment by JasonGross** [comment]
It's not quite up to date.  Should I update?  (This is involving `__`, which I assume is what you saw in https://github.com/cpitclaudel/company-coq/issues/85#issuecomment-186942529 ?)

**Comment by cpitclaudel** [comment]
No, I was confused about the single underscores, but I understand now. No need to update (though I did recently implement a feature that you requested a while ago about `Require Import`, which you may be interested in trying).

**Comment by JasonGross** [comment]
Which feature is this?  (Something about absolutizing things by default?)

**Comment by cpitclaudel** [comment]
Not by default; but I've added a link to `Require Import`s that you can click to absolutize them.

**Comment by cpitclaudel** [comment]
I've open an Emacs bug report. I'll try to find a workaround.

**Comment by cpitclaudel** [comment]
I think I have a decent workaround, but I'll give it a bit more testing before pushing it.

**Comment by cpitclaudel** [comment]
I just pushed a workaround. The idea is that `a__b` will still get displayed as `a sub b`, but only if you cursor is not near `__`. It it is, then the underscores will not be hidden. This should make the entire issue go away.

I'll close this for now, but do feel free to reopen if that fix doesn't work for you. We'll see if the Emacs bug points to another solution.

Thanks for the report!

**Comment by JasonGross** [comment]
Thanks!  Out of curiosity, where's the emacs bug you filed?

**Comment by cpitclaudel** [comment]
[bug#22761](https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-02/msg01255.html)
