### ISSUE TITLE
Typing `match goal with` should not leave me with a drop-down involving theorems whose names contain `with`

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#9]
It's rather annoying that whenever I type `match goal with RET`, I get `match goal refine_nt_with_only_t`.

**Comment by cpitclaudel** [comment]
Yes, that's annoying. I've had it on the back burner for a while; I need to find a good source of keywords. I guess a temporary workaround could work for now. I'll look into it.
