### ISSUE TITLE
Absolutization of `Require Import` should also be available for `Require`

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#92]
Currently, `Require Import` is underlined, but `Require` alone is not

**Comment by cpitclaudel** [comment]
Which others do I need to underline? Not Import alone, right?

**Comment by JasonGross** [comment]
No, not `Import`.  Just `Require`, `Require Import`, `Require Export`, `From ... Require ...`, `From .. Require Import ...`, and `From ... Require Export ...`, I believe.

**Comment by cpitclaudel** [comment]
Ok. I need to try to understand the From .. Require .. construct first. Do you know of a way to absolutize it, short of compiling and looking in the .glob?

**Comment by JasonGross** [comment]
To absolutize `From X Require Y`, run `Locate Module Y` after running the `Require` line, and filter for things starting with `X` (or is it things having `X` in the middle of them?)?

**Comment by cpitclaudel** [comment]
Ah. so it does require loading the actual module :/ Urgh.

**Comment by JasonGross** [comment]
Or run `coqdep` on a file with just the `From ... Require ...` line in it?  How do you do it for `Require Import ...` lines?

**Comment by cpitclaudel** [comment]
I do `Locate Library`, I think.

**Comment by cpitclaudel** [comment]
I've added tags to `Require` statements. I'll wait for specific requests about `From ... Import ...` before trying to tackle that particular issue (the current UI will need some changes).
