### ISSUE TITLE
for Notations, should symbols fold in quotes, at least in the Notation definition?

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#93]
Because Coq uses a quoted string to introduce a notation, shouldn't symbols that may be used by notations fold in quoted strings?  At least in the quoted string in the Notation definition?

Consider something like:

Notation "x <= y" := (mynums.le x y) : my_scope.

The "<=" is not folded in the Notation definition, but will be when used.  Might that be confusing?

**Comment by cpitclaudel** [comment]
Agreed! Probably only in notations. `prettify-symbols-mode` doesn't support this in Emacs 24, but it's feasible in Emacs 25.

**Comment by jonleivent** [comment]
After posting this, I realized that "\leq" does fold in quotes, but that of course the result of folding <= and \leq are two entirely different symbols that look exactly alike.  So, now I'm wondering if I started down a road to confusion by mixing both types of symbol folding...

**Comment by cpitclaudel** [comment]
Hmm, I'm a bit confuse. What do you mean by `\leq` folding.

**Comment by jonleivent** [comment]
Symbol completion on \leq produces ≤, just as symbol folding on <= does - but they're not the same symbol.

I think I need to make the following decision: do I want to have Unicode in my source files, or only in the result of displaying my source files in Company-Coq?  And the two should not be mixed.  So if I want Unicode in my source files, I need to turn off things like folding <=.  But, those are so much easier to type, and cover cases that are part of Coq syntax, such as =>, |-, etc.

**Comment by cpitclaudel** [comment]
Ah, I see what you mean.

Here's another possibility to consider: you can trim down company-coq-prettify-symbols-alist to only include Coq's syntax elements, and use unicode for everything else.

**Comment by cpitclaudel** [comment]
I've added a custom predicate; prettification will now work in code blocks inside comments, and in notation strings. Unfortunately, that predicate is only available in Emacs 25.
