### ISSUE TITLE
Do not prettify an intro pattern

### ISSUE THREAD

**Issue by Zimmi48** [cpitclaudel/company-coq#96]
Hello,

I don't know if this would be difficult or not but I think it would make more sense not to prettify the `*` symbol in the command `intros *` as it does not mean "times" there but has rather a closer meaning to the Kleene star.

The same remark holds for the pattern `in *` after a `simpl`, `lazy` or similar tactics.

Thanks,
Théo

PS: it's somewhat linked: it's funny have the `exists` prettified in the message `Error: thm already exists.` (When trying to start a new theorem with an already used name.)

**Comment by cpitclaudel** [comment]
Hey Théo,

`prettify-symbols-mode` can only be configured precisely starting with Emacs 25, so if we come up with a fix it will only be useful for bleeding-edge users.

That being said, it could be nice to fix this. I'm not entirely sure what the proper fix is, though; detecting the context in which a `*` is used is tricky, and it's often better to be consistently wrong.

Unprettifying `*` would be another option. I don't know how useful that prettification is, in fact. And I recently disabled the `~/¬` prettification, so I could disabled that one as well.

Opinions?

**Comment by cpitclaudel** [comment]
Regarding `exists`: indeed. But until PG gets semantically marked-up messages from Coq, I don't know what we can do to fix this :/ Let me know if you can think of something!

**Comment by Zimmi48** [comment]
Well, unprettifying `*` all the time could indeed be a good solution. Speaking for myself, I don't use the multiplication symbol that often.

**Comment by cpitclaudel** [comment]
Done! Thanks.
