### ISSUE TITLE
Folding of multi line signatures

### ISSUE THREAD

**Issue by JanBessai** [cpitclaudel/company-coq#98]
When defining a Lemma with a signature like this:

``` coq
Lemma foo:
  forall x y,
     P x y.
Proof.
 ... 
Qed.
```

outlining will fold it to

``` coq
Lemma foo:
```

so you cannot see the signature anymore. When signatures get larger, this happens a lot. It would be great, if there was a way to show everything up to `.` or `:=` in the outline.

**Comment by cpitclaudel** [comment]
Hi Jan,

It's been a while; sorry about this delay.
In a Coq buffer, can you try the following?

```
(setq-local outline-heading-end-regexp "\\.[ \t\n]")
(setq-local outline-regexp (concat "\n" company-coq-outline-regexp))
```

You can run each of these commands using `M-:`.

**Comment by JanBessai** [comment]
Thanks for looking into it!

For folding with C-c C-/ this works great. Just the full outline with C-c C-, remains cut after one line.

**Comment by cpitclaudel** [comment]
Cool, thanks for testing it. The `C-c C-,` outline is trickier to customize; I'll see what I can do there.
